In [1]:
%use dataframe
// %use lets-plot
// %use kandy
// %use plotly
import kotlinx.serialization.json.Json

In [17]:
val dir = "/Users/darronporter/Downloads/Dissertation/code/output/results"

// MCTS Easy as Agent 1
val mcts_easy_vs_mcts_random_records = "$dir/agent-1_MCTS_EASY_agent-2_MCTS_RANDOM_games_record.json"
val mcts_easy_vs_minimax_easy_records = "$dir/agent-1_MCTS_EASY_agent-2_MINIMAX_EASY_games_record.json"
val mcts_easy_vs_minimax_greedy_records = "$dir/agent-1_MCTS_EASY_agent-2_MINIMAX_GREEDY_games_record.json"

// MCTS Random as Agent 1
val mcts_random_vs_mcts_easy_records = "$dir/agent-1_MCTS_RANDOM_agent-2_MCTS_EASY_games_record.json"
val mcts_random_vs_minimax_easy_records = "$dir/agent-1_MCTS_RANDOM_agent-2_MINIMAX_EASY_games_record.json"
val mcts_random_vs_minimax_greedy_records = "$dir/agent-1_MCTS_RANDOM_agent-2_MINIMAX_GREEDY_games_record.json"

// Minimax Easy as Agent 1
val minimax_easy_vs_mcts_easy_records = "$dir/agent-1_MINIMAX_EASY_agent-2_MCTS_EASY_games_record.json"
val minimax_easy_vs_mcts_random_records = "$dir/agent-1_MINIMAX_EASY_agent-2_MCTS_RANDOM_games_record.json"
val minimax_easy_vs_minimax_greedy_records = "$dir/agent-1_MINIMAX_EASY_agent-2_MINIMAX_GREEDY_games_record.json"

// Minimax Greedy as Agent 1
val minimax_greedy_vs_mcts_easy_records = "$dir/agent-1_MINIMAX_GREEDY_agent-2_MCTS_EASY_games_record.json"
val minimax_greedy_vs_mcts_random_records = "$dir/agent-1_MINIMAX_GREEDY_agent-2_MCTS_RANDOM_games_record.json"
val minimax_greedy_vs_minimax_easy_records = "$dir/agent-1_MINIMAX_GREEDY_agent-2_MINIMAX_EASY_games_record.json"

In [93]:
val mcts_e_vs_mcts_r = DataFrame.readJson(mcts_easy_vs_mcts_random_records)
val mcts_e_vs_mm_e = DataFrame.readJson(mcts_easy_vs_minimax_easy_records)
val mcts_e_vs_mm_g = DataFrame.readJson(mcts_easy_vs_minimax_greedy_records)
val mcts_r_vs_mcts_e = DataFrame.readJson(mcts_random_vs_mcts_easy_records)
val mcts_r_vs_mm_e = DataFrame.readJson(mcts_random_vs_minimax_easy_records)
val mcts_r_vs_mm_g = DataFrame.readJson(mcts_random_vs_minimax_greedy_records)
val mm_e_vs_mcts_e = DataFrame.readJson(minimax_easy_vs_mcts_easy_records)
val mm_e_vs_mcts_r = DataFrame.readJson(minimax_easy_vs_mcts_random_records)
val mm_e_vs_mm_g = DataFrame.readJson(minimax_easy_vs_minimax_greedy_records)
val mm_g_vs_mcts_e = DataFrame.readJson(minimax_greedy_vs_mcts_easy_records)
val mm_g_vs_mcts_r = DataFrame.readJson(minimax_greedy_vs_mcts_random_records)
val mm_g_vs_mm_e = DataFrame.readJson(minimax_greedy_vs_minimax_easy_records)

CompositeException in converters (fields callbacks): 3 exceptions occurred.
CompositeException in converters (fields callbacks): 3 exceptions occurred.
-------------------------------
Exception 0:
org.jetbrains.kotlinx.jupyter.exceptions.ReplCompilerException: Line_207.jupyter.kts (1:1 - 2:26) 'public abstract val gameState: Line_22_jupyter.GameState defined in Line_207_jupyter._DataFrameType6' clashes with 'public abstract val gameState: Line_184_jupyter.Matrx.GameState defined in Line_184_jupyter.Matrx': property types are incompatible
at Cell In[0], line 5, column 19: No cast needed
	at org.jetbrains.kotlinx.jupyter.compiler.CompiledScriptCache.deserializeResult-wUyqLnw(CompiledScriptCache.kt:36)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.internalEvaluator$lambda$0(ReplForJupyterImpl.kt:347)
	at org.jetbrains.kotlinx.jupyter.repl.impl.InternalEvaluatorImpl.eval(InternalEvaluatorImpl.kt:129)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl.execute_W38Nk0s$lambda$0$1(CellExecutorImpl.kt:95)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.withHost(ReplForJupyterImpl.kt:729)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl.execute-W38Nk0s(CellExecutorImpl.kt:93)
	at org.jetbrains.kotlinx.jupyter.repl.execution.CellExecutor.execute-W38Nk0s$default(CellExecutor.kt:14)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl$ExecutionContext.execute(CellExecutorImpl.kt:306)
	at org.jetbrains.kotlinx.dataframe.jupyter.ExecuteKt.execute(execute.kt:15)
	at org.jetbrains.kotlinx.dataframe.jupyter.ExecuteKt.execute(execute.kt:32)
	at org.jetbrains.kotlinx.dataframe.jupyter.Integration.updateAnyFrameVariable(Integration.kt:138)
	at org.jetbrains.kotlinx.dataframe.jupyter.Integration.access$updateAnyFrameVariable(Integration.kt:63)
	at org.jetbrains.kotlinx.dataframe.jupyter.Integration$onLoaded$5.execution$lambda$0(Integration.kt:330)
	at org.jetbrains.kotlinx.jupyter.api.libraries.FieldHandlerFactory.createUpdateExecution$lambda$0(FieldHandlerFactory.kt:42)
	at org.jetbrains.kotlinx.jupyter.codegen.FieldsProcessorImplKt.executeEx(FieldsProcessorImpl.kt:102)
	at org.jetbrains.kotlinx.jupyter.codegen.FieldsProcessorImplKt.access$executeEx(FieldsProcessorImpl.kt:1)
	at org.jetbrains.kotlinx.jupyter.codegen.FieldsProcessorImpl.process(FieldsProcessorImpl.kt:51)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl.execute_W38Nk0s$lambda$0$2(CellExecutorImpl.kt:114)
	at org.jetbrains.kotlinx.jupyter.config.LoggingKt.catchAll(Logging.kt:33)
	at org.jetbrains.kotlinx.jupyter.config.LoggingKt.catchAll$default(Logging.kt:27)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl.execute-W38Nk0s(CellExecutorImpl.kt:113)
	at org.jetbrains.kotlinx.jupyter.repl.execution.CellExecutor.execute-W38Nk0s$default(CellExecutor.kt:14)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.evaluateUserCode-wNURfNM(ReplForJupyterImpl.kt:578)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.evalExImpl(ReplForJupyterImpl.kt:458)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.evalEx$lambda$0(ReplForJupyterImpl.kt:452)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.withEvalContext(ReplForJupyterImpl.kt:441)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.evalEx(ReplForJupyterImpl.kt:451)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.processExecuteRequest$lambda$0$0$0(IdeCompatibleMessageRequestProcessor.kt:179)
	at org.jetbrains.kotlinx.jupyter.streams.BlockingSubstitutionEngine.withDataSubstitution(SubstitutionEngine.kt:124)
	at org.jetbrains.kotlinx.jupyter.streams.StreamSubstitutionManager.withSubstitutedStreams(StreamSubstitutionManager.kt:118)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.withForkedIn(IdeCompatibleMessageRequestProcessor.kt:373)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.evalWithIO$lambda$0$0(IdeCompatibleMessageRequestProcessor.kt:386)
	at org.jetbrains.kotlinx.jupyter.streams.BlockingSubstitutionEngine.withDataSubstitution(SubstitutionEngine.kt:124)
	at org.jetbrains.kotlinx.jupyter.streams.StreamSubstitutionManager.withSubstitutedStreams(StreamSubstitutionManager.kt:118)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.withForkedErr(IdeCompatibleMessageRequestProcessor.kt:363)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.evalWithIO$lambda$0(IdeCompatibleMessageRequestProcessor.kt:385)
	at org.jetbrains.kotlinx.jupyter.streams.BlockingSubstitutionEngine.withDataSubstitution(SubstitutionEngine.kt:124)
	at org.jetbrains.kotlinx.jupyter.streams.StreamSubstitutionManager.withSubstitutedStreams(StreamSubstitutionManager.kt:118)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.withForkedOut(IdeCompatibleMessageRequestProcessor.kt:356)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.evalWithIO(IdeCompatibleMessageRequestProcessor.kt:384)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.processExecuteRequest$lambda$0$0(IdeCompatibleMessageRequestProcessor.kt:178)
	at org.jetbrains.kotlinx.jupyter.execution.JupyterExecutorImpl$Task.execute(JupyterExecutorImpl.kt:41)
	at org.jetbrains.kotlinx.jupyter.execution.JupyterExecutorImpl.executorThread$lambda$0(JupyterExecutorImpl.kt:81)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
-------------------------------
Exception 1:
org.jetbrains.kotlinx.jupyter.exceptions.ReplCompilerException: Line_222.jupyter.kts (1:1 - 2:26) 'public abstract val gameState: Line_22_jupyter.GameState defined in Line_222_jupyter._DataFrameType6' clashes with 'public abstract val gameState: Line_184_jupyter.Matrx.GameState defined in Line_184_jupyter.Matrx': property types are incompatible
at Cell In[0], line 5, column 15: No cast needed
	at org.jetbrains.kotlinx.jupyter.compiler.CompiledScriptCache.deserializeResult-wUyqLnw(CompiledScriptCache.kt:36)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.internalEvaluator$lambda$0(ReplForJupyterImpl.kt:347)
	at org.jetbrains.kotlinx.jupyter.repl.impl.InternalEvaluatorImpl.eval(InternalEvaluatorImpl.kt:129)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl.execute_W38Nk0s$lambda$0$1(CellExecutorImpl.kt:95)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.withHost(ReplForJupyterImpl.kt:729)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl.execute-W38Nk0s(CellExecutorImpl.kt:93)
	at org.jetbrains.kotlinx.jupyter.repl.execution.CellExecutor.execute-W38Nk0s$default(CellExecutor.kt:14)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl$ExecutionContext.execute(CellExecutorImpl.kt:306)
	at org.jetbrains.kotlinx.dataframe.jupyter.ExecuteKt.execute(execute.kt:15)
	at org.jetbrains.kotlinx.dataframe.jupyter.ExecuteKt.execute(execute.kt:32)
	at org.jetbrains.kotlinx.dataframe.jupyter.Integration.updateAnyFrameVariable(Integration.kt:138)
	at org.jetbrains.kotlinx.dataframe.jupyter.Integration.access$updateAnyFrameVariable(Integration.kt:63)
	at org.jetbrains.kotlinx.dataframe.jupyter.Integration$onLoaded$5.execution$lambda$0(Integration.kt:330)
	at org.jetbrains.kotlinx.jupyter.api.libraries.FieldHandlerFactory.createUpdateExecution$lambda$0(FieldHandlerFactory.kt:42)
	at org.jetbrains.kotlinx.jupyter.codegen.FieldsProcessorImplKt.executeEx(FieldsProcessorImpl.kt:102)
	at org.jetbrains.kotlinx.jupyter.codegen.FieldsProcessorImplKt.access$executeEx(FieldsProcessorImpl.kt:1)
	at org.jetbrains.kotlinx.jupyter.codegen.FieldsProcessorImpl.process(FieldsProcessorImpl.kt:51)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl.execute_W38Nk0s$lambda$0$2(CellExecutorImpl.kt:114)
	at org.jetbrains.kotlinx.jupyter.config.LoggingKt.catchAll(Logging.kt:33)
	at org.jetbrains.kotlinx.jupyter.config.LoggingKt.catchAll$default(Logging.kt:27)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl.execute-W38Nk0s(CellExecutorImpl.kt:113)
	at org.jetbrains.kotlinx.jupyter.repl.execution.CellExecutor.execute-W38Nk0s$default(CellExecutor.kt:14)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.evaluateUserCode-wNURfNM(ReplForJupyterImpl.kt:578)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.evalExImpl(ReplForJupyterImpl.kt:458)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.evalEx$lambda$0(ReplForJupyterImpl.kt:452)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.withEvalContext(ReplForJupyterImpl.kt:441)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.evalEx(ReplForJupyterImpl.kt:451)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.processExecuteRequest$lambda$0$0$0(IdeCompatibleMessageRequestProcessor.kt:179)
	at org.jetbrains.kotlinx.jupyter.streams.BlockingSubstitutionEngine.withDataSubstitution(SubstitutionEngine.kt:124)
	at org.jetbrains.kotlinx.jupyter.streams.StreamSubstitutionManager.withSubstitutedStreams(StreamSubstitutionManager.kt:118)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.withForkedIn(IdeCompatibleMessageRequestProcessor.kt:373)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.evalWithIO$lambda$0$0(IdeCompatibleMessageRequestProcessor.kt:386)
	at org.jetbrains.kotlinx.jupyter.streams.BlockingSubstitutionEngine.withDataSubstitution(SubstitutionEngine.kt:124)
	at org.jetbrains.kotlinx.jupyter.streams.StreamSubstitutionManager.withSubstitutedStreams(StreamSubstitutionManager.kt:118)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.withForkedErr(IdeCompatibleMessageRequestProcessor.kt:363)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.evalWithIO$lambda$0(IdeCompatibleMessageRequestProcessor.kt:385)
	at org.jetbrains.kotlinx.jupyter.streams.BlockingSubstitutionEngine.withDataSubstitution(SubstitutionEngine.kt:124)
	at org.jetbrains.kotlinx.jupyter.streams.StreamSubstitutionManager.withSubstitutedStreams(StreamSubstitutionManager.kt:118)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.withForkedOut(IdeCompatibleMessageRequestProcessor.kt:356)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.evalWithIO(IdeCompatibleMessageRequestProcessor.kt:384)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.processExecuteRequest$lambda$0$0(IdeCompatibleMessageRequestProcessor.kt:178)
	at org.jetbrains.kotlinx.jupyter.execution.JupyterExecutorImpl$Task.execute(JupyterExecutorImpl.kt:41)
	at org.jetbrains.kotlinx.jupyter.execution.JupyterExecutorImpl.executorThread$lambda$0(JupyterExecutorImpl.kt:81)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
-------------------------------
Exception 2:
org.jetbrains.kotlinx.jupyter.exceptions.ReplCompilerException: Line_227.jupyter.kts (1:1 - 2:26) 'public abstract val gameState: Line_22_jupyter.GameState defined in Line_227_jupyter._DataFrameType6' clashes with 'public abstract val gameState: Line_184_jupyter.Matrx.GameState defined in Line_184_jupyter.Matrx': property types are incompatible
at Cell In[0], line 5, column 15: No cast needed
	at org.jetbrains.kotlinx.jupyter.compiler.CompiledScriptCache.deserializeResult-wUyqLnw(CompiledScriptCache.kt:36)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.internalEvaluator$lambda$0(ReplForJupyterImpl.kt:347)
	at org.jetbrains.kotlinx.jupyter.repl.impl.InternalEvaluatorImpl.eval(InternalEvaluatorImpl.kt:129)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl.execute_W38Nk0s$lambda$0$1(CellExecutorImpl.kt:95)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.withHost(ReplForJupyterImpl.kt:729)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl.execute-W38Nk0s(CellExecutorImpl.kt:93)
	at org.jetbrains.kotlinx.jupyter.repl.execution.CellExecutor.execute-W38Nk0s$default(CellExecutor.kt:14)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl$ExecutionContext.execute(CellExecutorImpl.kt:306)
	at org.jetbrains.kotlinx.dataframe.jupyter.ExecuteKt.execute(execute.kt:15)
	at org.jetbrains.kotlinx.dataframe.jupyter.ExecuteKt.execute(execute.kt:32)
	at org.jetbrains.kotlinx.dataframe.jupyter.Integration.updateAnyFrameVariable(Integration.kt:138)
	at org.jetbrains.kotlinx.dataframe.jupyter.Integration.access$updateAnyFrameVariable(Integration.kt:63)
	at org.jetbrains.kotlinx.dataframe.jupyter.Integration$onLoaded$5.execution$lambda$0(Integration.kt:330)
	at org.jetbrains.kotlinx.jupyter.api.libraries.FieldHandlerFactory.createUpdateExecution$lambda$0(FieldHandlerFactory.kt:42)
	at org.jetbrains.kotlinx.jupyter.codegen.FieldsProcessorImplKt.executeEx(FieldsProcessorImpl.kt:102)
	at org.jetbrains.kotlinx.jupyter.codegen.FieldsProcessorImplKt.access$executeEx(FieldsProcessorImpl.kt:1)
	at org.jetbrains.kotlinx.jupyter.codegen.FieldsProcessorImpl.process(FieldsProcessorImpl.kt:51)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl.execute_W38Nk0s$lambda$0$2(CellExecutorImpl.kt:114)
	at org.jetbrains.kotlinx.jupyter.config.LoggingKt.catchAll(Logging.kt:33)
	at org.jetbrains.kotlinx.jupyter.config.LoggingKt.catchAll$default(Logging.kt:27)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl.execute-W38Nk0s(CellExecutorImpl.kt:113)
	at org.jetbrains.kotlinx.jupyter.repl.execution.CellExecutor.execute-W38Nk0s$default(CellExecutor.kt:14)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.evaluateUserCode-wNURfNM(ReplForJupyterImpl.kt:578)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.evalExImpl(ReplForJupyterImpl.kt:458)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.evalEx$lambda$0(ReplForJupyterImpl.kt:452)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.withEvalContext(ReplForJupyterImpl.kt:441)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.evalEx(ReplForJupyterImpl.kt:451)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.processExecuteRequest$lambda$0$0$0(IdeCompatibleMessageRequestProcessor.kt:179)
	at org.jetbrains.kotlinx.jupyter.streams.BlockingSubstitutionEngine.withDataSubstitution(SubstitutionEngine.kt:124)
	at org.jetbrains.kotlinx.jupyter.streams.StreamSubstitutionManager.withSubstitutedStreams(StreamSubstitutionManager.kt:118)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.withForkedIn(IdeCompatibleMessageRequestProcessor.kt:373)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.evalWithIO$lambda$0$0(IdeCompatibleMessageRequestProcessor.kt:386)
	at org.jetbrains.kotlinx.jupyter.streams.BlockingSubstitutionEngine.withDataSubstitution(SubstitutionEngine.kt:124)
	at org.jetbrains.kotlinx.jupyter.streams.StreamSubstitutionManager.withSubstitutedStreams(StreamSubstitutionManager.kt:118)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.withForkedErr(IdeCompatibleMessageRequestProcessor.kt:363)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.evalWithIO$lambda$0(IdeCompatibleMessageRequestProcessor.kt:385)
	at org.jetbrains.kotlinx.jupyter.streams.BlockingSubstitutionEngine.withDataSubstitution(SubstitutionEngine.kt:124)
	at org.jetbrains.kotlinx.jupyter.streams.StreamSubstitutionManager.withSubstitutedStreams(StreamSubstitutionManager.kt:118)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.withForkedOut(IdeCompatibleMessageRequestProcessor.kt:356)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.evalWithIO(IdeCompatibleMessageRequestProcessor.kt:384)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.processExecuteRequest$lambda$0$0(IdeCompatibleMessageRequestProcessor.kt:178)
	at org.jetbrains.kotlinx.jupyter.execution.JupyterExecutorImpl$Task.execute(JupyterExecutorImpl.kt:41)
	at org.jetbrains.kotlinx.jupyter.execution.JupyterExecutorImpl.executorThread$lambda$0(JupyterExecutorImpl.kt:81)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
-------------------------------

In [94]:
val dataframes = listOf<DataFrame<*>>(
	mcts_e_vs_mcts_r, mcts_e_vs_mm_e, mcts_e_vs_mm_g, mcts_r_vs_mcts_e, mcts_r_vs_mm_e, mcts_r_vs_mm_g, mm_e_vs_mcts_e, mm_e_vs_mcts_r, mm_e_vs_mm_g, mm_g_vs_mcts_e, mm_g_vs_mcts_r, mm_g_vs_mm_e
)

In [95]:
@DataSchema
interface Matrx {
	val gameId: Int
	val gameState: GameState
	val seed: Long
	val timestamp: Long
	val turn: Int
	val winner: Winner

	@DataSchema(isOpen = false)
	interface Bitboard {
		val blackDVONNLayer: List<Long>
		val blackGIPF: Long?
		val blackPUNCTLayer: List<Long>
		val blackPotentials: Long
		val blackTAMSK: Long?
		val blackYINSH: Long?
		val blackZERTZ: Long?
		val whiteDVONNLayer: List<Long>
		val whiteGIPF: Long?
		val whitePUNCTLayer: List<Long>
		val whitePotentials: Long?
		val whiteTAMSK: Long?
		val whiteYINSH: Long?
		val whiteZERTZ: Long?
	}

	@DataSchema(isOpen = false)
	interface CurrentPlayer {
		val capturedPieces: List<Int>
		val model: String
		val name: String
		val piecesInReserve: List<Int>
		val strength: String
		val timeControl: Boolean
		val useRAVE: Boolean
	}

	@DataSchema(isOpen = false)
	interface GameState {
		val bitboard: Bitboard
		val currentPlayer: CurrentPlayer
		val nextPlayer: CurrentPlayer
	}

	@DataSchema(isOpen = false)
	interface Winner {
		val first: CurrentPlayer
		val second: String
	}
}

In [16]:
dataframes.map { it.head(5)  }

[   gameId                 seed     timestamp turn                                   winner                                gameState
 0     13   635341749637700507 1786520344214   58 { first:{ name:BLACK, model:MCTS, str... { currentPlayer:{ name:WHITE, model:M...
 1      3 -2691344208950304075 1786520344214   60 { first:{ name:BLACK, model:MCTS, str... { currentPlayer:{ name:WHITE, model:M...
 2      9 -8074032627088668105 1786520344214  118 { first:{ name:BLACK, model:MCTS, str... { currentPlayer:{ name:WHITE, model:M...
 3      4  8709371765740070622 1786520344214   78 { first:{ name:BLACK, model:MCTS, str... { currentPlayer:{ name:WHITE, model:M...
 4      5  1663342292303182563 1786520344214   90 { first:{ name:BLACK, model:MCTS, str... { currentPlayer:{ name:WHITE, model:M...
,    gameId                 seed     timestamp turn                                   winner                                gameState
 0      4  8709371765712937210 1786522570940   59 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 1      7  6018029068535100477 1786522570940   75 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 2      3 -2691344208956726127 1786522570940   33 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 3      1 -7046030985074217797 1786522570940   73 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 4     10  3326683072721832060 1786522570940   89 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
,    gameId                 seed     timestamp turn                                   winner                                gameState
 0     11 -3719345026324948895 1786521472147   60 { first:{ name:BLACK, model:MCTS, str... { currentPlayer:{ name:WHITE, model:M...
 1      2  4354684989610046636 1786521472147   53 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 2      3 -2691344208951428935 1786521472147   81 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 3     10  3326683072691344468 1786521472147  105 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 4     12  7681369848689433722 1786521472147  106 { first:{ name:BLACK, model:MCTS, str... { currentPlayer:{ name:WHITE, model:M...
,    gameId                 seed     timestamp turn                                   winner                                gameState
 0     11 -3719345026319283197 1786524784881  107 { first:{ name:WHITE, model:MCTS, str... { currentPlayer:{ name:BLACK, model:M...
 1     12  7681369848669079576 1786524784881   63 { first:{ name:WHITE, model:MCTS, str... { currentPlayer:{ name:BLACK, model:M...
 2      5  1663342292315452557 1786524784881  103 { first:{ name:WHITE, model:MCTS, str... { currentPlayer:{ name:BLACK, model:M...
 3      8 -1028003428514711476 1786524784881   81 { first:{ name:WHITE, model:MCTS, str... { currentPlayer:{ name:BLACK, model:M...
 4      4  8709371765710989488 1786524784881   65 { first:{ name:WHITE, model:MCTS, str... { currentPlayer:{ name:BLACK, model:M...
,    gameId                 seed     timestamp turn                                   winner                                gameState
 0      6 -5382685806619789226 1786527944757   53 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 1      3 -2691344208962100201 1786527944757  115 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 2     10  3326683072718817530 1786527944757   43 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 3      4  8709371765718311036 1786527944757  107 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 4     14 -6410687448882358002 1786527944757   99 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
,    gameId                 seed     timestamp turn                                   winner                                gameState
 0      8 -1028003428516214649 1786525755447   86 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 1      4  8709371765711853691 1786525755447  116 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 2     12  7681369848668387539 1786525755447  114 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 3      5  1663342292314866758 1786525755447   80 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 4      3 -2691344208955646960 1786525755447  120 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
,    gameId                 seed     timestamp turn                                   winner                                gameState
 0     14 -6410687448868128439 1786475327616  110 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 1      1 -7046030985020814214 1786475327616   90 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 2      3 -2691344208838179760 1786475327616  108 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 3      8 -1028003428633554745 1786475327616  126 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 4      4  8709371765829386299 1786475327616   96 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
,    gameId                 seed     timestamp turn                                   winner                                gameState
 0     14 -6410687448169227192 1786098455942   78 { name:BLACK, model:MINIMAX, strength... { currentPlayer:{ name:WHITE, model:M...
 1      2  4354684990061505860 1786098455942   84 { name:BLACK, model:MINIMAX, strength... { currentPlayer:{ name:WHITE, model:M...
 2      6 -5382685806324515568 1786098455942   76 { name:BLACK, model:MINIMAX, strength... { currentPlayer:{ name:WHITE, model:M...
 3      7  6018029068850229757 1786098455942   91 { name:WHITE, model:MCTS, piecesInRes... { currentPlayer:{ name:BLACK, model:M...
 4     12  7681369849380881810 1786098455942   86 { name:BLACK, model:MINIMAX, strength... { currentPlayer:{ name:WHITE, model:M...
,    gameId                 seed     timestamp turn                                   winner                                gameState
 0      8 -1028003428518361891 1786523182213  101 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 1     16 -2056005345692375771 1786523182213   83 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 2      6 -5382685806623552501 1786523182213   91 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 3     11 -3719345026318782318 1786523182213  116 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 4      2  4354684989627997279 1786523182213  119 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
,    gameId                 seed     timestamp turn                                   winner                                gameState
 0      5  1663342292395812189 1786477185349   85 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 1     11 -3719345026365006381 1786477185349  111 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 2      4  8709371765836446048 1786477185349  105 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 3     13   635341749679473701 1786477185349  111 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 4      9 -8074032627116878455 1786477185349   93 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
,    gameId                 seed     timestamp turn                                   winner                                gameState
 0     13   635341749641799406 1786515008526   80 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 1     12  7681369848695913219 1786515008526   52 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 2      2  4354684989603009493 1786515008526   96 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 3      1 -7046030985047189526 1786515008526  108 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 4      8 -1028003428526961833 1786515008526   82 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
,    gameId                 seed     timestamp turn                                   winner                                gameState
 0      4  8709371765711988750 1786525882475   98 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 1      2  4354684989630668912 1786525882475  100 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 2      6 -5382685806626115548 1786525882475   76 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 3     13   635341749668402507 1786525882475  148 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 4     12  7681369848667981990 1786525882475  106 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
]

In [39]:
mcts_e_vs_mcts_r

In [19]:
mcts_e_vs_mcts_r.winner.first.name.valueCounts()

name,count
BLACK,975
WHITE,25

In [21]:
mcts_e_vs_mcts_r.winner.second.valueCounts()

second,count
MadeTheLastMove,893
CapturedAllGIPFPieces,107

In [26]:
mcts_r_vs_mcts_e.winner.first.name.valueCounts()

name,count
WHITE,979
BLACK,21

In [25]:
mcts_r_vs_mcts_e.winner.second.valueCounts()

second,count
MadeTheLastMove,896
CapturedAllGIPFPieces,104

In [32]:
dataframes.map { it["winner"]["first"]["strength"].valueCounts() }

[   strength count
 0   RANDOM   975
 1     EASY    25
,    strength count
 0     EASY  1000
,    strength count
 0   GREEDY  1942
 1     EASY    71
,    strength count
 0   RANDOM   979
 1     EASY    21
,    strength count
 0     EASY   799
 1   RANDOM   199
,    strength count
 0   GREEDY   639
 1   RANDOM   361
,    strength count
 0     EASY  1000
,    strength count
 0     EASY   838
 1   RANDOM   162
,    strength count
 0     EASY   728
 1   GREEDY   272
,    strength count
 0   GREEDY   966
 1     EASY    34
,    strength count
 0   GREEDY   631
 1   RANDOM   369
,    strength count
 0     EASY   670
 1   GREEDY   330
]

In [54]:
dataframes.forEach { println(it.getColumnGroup("winner").getColumnGroup("first").select { cols(0..2) }.valueCounts()) }

    name model strength count
 0 BLACK  MCTS   RANDOM   975
 1 WHITE  MCTS     EASY    25

    name   model strength count
 0 BLACK MINIMAX     EASY   949
 1 WHITE    MCTS     EASY    51

    name   model strength count
 0 BLACK MINIMAX   GREEDY  1942
 1 WHITE    MCTS     EASY    71

    name model strength count
 0 WHITE  MCTS   RANDOM   979
 1 BLACK  MCTS     EASY    21

    name   model strength count
 0 BLACK MINIMAX     EASY   799
 1 WHITE    MCTS   RANDOM   199

    name   model strength count
 0 BLACK MINIMAX   GREEDY   639
 1 WHITE    MCTS   RANDOM   361

    name   model strength count
 0 WHITE MINIMAX     EASY   959
 1 BLACK    MCTS     EASY    41

    name   model strength count
 0 WHITE MINIMAX     EASY   838
 1 BLACK    MCTS   RANDOM   162

    name   model strength count
 0 WHITE MINIMAX     EASY   728
 1 BLACK MINIMAX   GREEDY   272

    name   model strength count
 0 WHITE MINIMAX   GREEDY   966
 1 BLACK    MCTS     EASY    34

    name   model strength count
 0 WHITE MINIMAX   GREEDY   631
 1 BLACK    MCTS   RANDOM   369

    name   model strength count
 0 BLACK MINIMAX     EASY   670
 1 WHITE MINIMAX   GREEDY   330

In [74]:
mcts_e_vs_mcts_r.groupBy { winner.second }.aggregate {
	it.getColumnGroup("winner").getColumnGroup("first").select { cols(0..2) }.valueCounts()
}.toStandaloneHtml()

In [75]:
mcts_r_vs_mcts_e.groupBy { winner.second }.aggregate {
	it.getColumnGroup("winner").getColumnGroup("first").select { cols(0..2) }.valueCounts()
}.toStandaloneHtml()

In [82]:
mcts_e_vs_mcts_r.generateInterfaces("Matrx")

@DataSchema
interface Matrx {
    val gameId: Int
    val gameState: GameState
    val seed: Long
    val timestamp: Long
    val turn: Int
    val winner: Winner

    @DataSchema(isOpen = false)
    interface Bitboard {
        val blackDVONNLayer: List<Long>
        val blackGIPF: Long?
        val blackPUNCTLayer: List<Long>
        val blackPotentials: Long
        val blackTAMSK: Long?
        val blackYINSH: Long?
        val blackZERTZ: Long?
        val whiteDVONNLayer: List<Long>
        val whiteGIPF: Long?
        val whitePUNCTLayer: List<Long>
        val whitePotentials: Long?
        val whiteTAMSK: Long?
        val whiteYINSH: Long?
        val whiteZERTZ: Long?
    }

    @DataSchema(isOpen = false)
    interface CurrentPlayer {
        val capturedPieces: List<Int>
        val model: String
        val name: String
        val piecesInReserve: List<Int>
        val strength: String
        val timeControl: Boolean
        val useRAVE: Boolean
    }

    @DataSchema(isOpen = false)
    interface GameState {
        val bitboard: Bitboard
        val currentPlayer: CurrentPlayer
        val nextPlayer: CurrentPlayer
    }

    @DataSchema(isOpen = false)
    interface Winner {
        val first: CurrentPlayer
        val second: String
    }
}

In [97]:
val concat = dataframes.concat().cast<Matrx>()

In [98]:
concat.select {
	winner.second and winner.first.cols(0..2)
}.valueCounts()

second,name,model,strength,count
MadeTheLastMove,WHITE,MINIMAX,EASY,2305
MadeTheLastMove,BLACK,MINIMAX,EASY,2204
MadeTheLastMove,WHITE,MINIMAX,GREEDY,1659
MadeTheLastMove,BLACK,MINIMAX,GREEDY,1354
MadeTheLastMove,BLACK,MCTS,RANDOM,1348
MadeTheLastMove,WHITE,MCTS,RANDOM,1183
CapturedAllGIPFPieces,WHITE,MINIMAX,GREEDY,268
CapturedAllGIPFPieces,BLACK,MINIMAX,GREEDY,221
CapturedAllGIPFPieces,WHITE,MINIMAX,EASY,220
CapturedAllGIPFPieces,BLACK,MINIMAX,EASY,214
CapturedAllGIPFPieces,WHITE,MCTS,RANDOM,164
CapturedAllGIPFPieces,BLACK,MCTS,RANDOM,158
MadeTheLastMove,WHITE,MCTS,EASY,103
MadeTheLastMove,BLACK,MCTS,EASY,93
CapturedAllGIPFPieces,WHITE,MCTS,EASY,4
CapturedAllGIPFPieces,BLACK,MCTS,EASY,3

In [96]:
dataframes.map { it.count() }

[1000, 1000, 1001, 1000, 998, 1001, 1000, 1000, 1000, 1000, 1000, 1000]

In [103]:
val totalGames = 6000.0

In [110]:
val wins = concat.select {
	winner.second and winner.first.select { model and strength }
}.valueCounts()

In [111]:
wins.add("win_percentage") {
	(count / totalGames) * 100.0
}

second,model,strength,count,win_percentage
MadeTheLastMove,MINIMAX,EASY,4509,75.150000
MadeTheLastMove,MINIMAX,GREEDY,3013,50.216667
MadeTheLastMove,MCTS,RANDOM,2531,42.183333
CapturedAllGIPFPieces,MINIMAX,GREEDY,489,8.150000
CapturedAllGIPFPieces,MINIMAX,EASY,434,7.233333
CapturedAllGIPFPieces,MCTS,RANDOM,322,5.366667
MadeTheLastMove,MCTS,EASY,196,3.266667
CapturedAllGIPFPieces,MCTS,EASY,7,0.116667

In [114]:
val winning = concat.select {
	winner.first.select { model and strength }
}.valueCounts()

In [115]:
winning.add("win_percentage") {
	(count / totalGames) * 100.0
}

model,strength,count,win_percentage
MINIMAX,EASY,4943,82.383333
MINIMAX,GREEDY,3502,58.366667
MCTS,RANDOM,2853,47.550000
MCTS,EASY,203,3.383333