In [1]:
USE {
	dependencies("org.duckdb:duckdb_jdbc:1.5.5.1")
}

In [2]:
%use dataframe
// %use lets-plot
// %use kandy
// %use plotly

import kotlinx.serialization.json.Json

In [3]:
import org.jetbrains.kotlinx.dataframe.io.DbConnectionConfig
import org.jetbrains.kotlinx.dataframe.schema.DataFrameSchema

In [33]:
@DataSchema
interface Matrx {
	val gameId: Int
	val gameState: GameState
	val seed: Long
	val timestamp: Long
	val turn: Int
	val winner: Winner

	@DataSchema(isOpen = false)
	interface CurrentPlayer {
		val capturedPieces: List<Int>
		val depth: Int
		val enableFPU: Boolean
		val enablePW: Boolean
		val iterations: Int
		val model: String
		val name: String
		val piecesInReserve: List<Int>
		val strength: String
		val timeControl: Boolean
		val timeDuration: String
		val useRAVE: Boolean
	}

	@DataSchema(isOpen = false)
	interface GameState {
		val currentPlayer: CurrentPlayer
		val nextPlayer: CurrentPlayer
		val turnDuration: TurnDuration
	}

	@DataSchema(isOpen = false)
	interface Winner {
		val loser: CurrentPlayer
		val winCondition: String
		val winner: CurrentPlayer
	}
}

In [4]:
val url = "jdbc:duckdb:/Users/darronporter/Downloads/Dissertation/code/output/results/gcloud_time_control_results_2026-08-27/time_control.duckdb"
val username = "duckdb"
val password = "password"

val dbConfig = DbConnectionConfig(url, username, password)

val tableName = "game_results"

In [16]:
val raw = DataFrame.readSqlTable(dbConfig, tableName)

In [8]:
val winner = DataFrame.readSqlQuery(
	dbConfig,
	sqlQuery = "SELECT seed, turn, winner.winCondition, winner.winner, winner.loser FROM game_results",
)

In [34]:
val df = raw.cast<Matrx>()

In [35]:
df.head()

gameId,seed,timestamp,turn,winner,,,gameState,,,,,filename
,,,,winner,winCondition,loser,currentPlayer,nextPlayer,bitboard,turnMoves,turnDuration,
9,-8074032581223329569,1787828276366,29,"{""name""=WHITE, model=MCTS, strength=N...",CapturedAllGIPFPieces,"{""name""=BLACK, model=MINIMAX, strengt...","{""name""=BLACK, model=MINIMAX, strengt...","{""name""=WHITE, model=MCTS, strength=N...","{whiteGIPF=33554432, whiteDVONNLayer=...","{""1""= ...","{""1""=[1011], ""2""=[1006], ""3""=[1000], ...",./agent-1_MCTS_iterations-0-depth-1_a...
8,-1028003326894183222,1787828276366,41,"{""name""=WHITE, model=MCTS, strength=N...",CapturedAllGIPFPieces,"{""name""=BLACK, model=MINIMAX, strengt...","{""name""=BLACK, model=MINIMAX, strengt...","{""name""=WHITE, model=MCTS, strength=N...","{whiteGIPF=618475290624, whiteDVONNLa...","{""1""= ...","{""1""=[1000], ""2""=[767], ""3""=[1001], ""...",./agent-1_MCTS_iterations-0-depth-1_a...
22,-7438692794564598356,1787828276366,43,"{""name""=WHITE, model=MCTS, strength=N...",CapturedAllGIPFPieces,"{""name""=BLACK, model=MINIMAX, strengt...","{""name""=BLACK, model=MINIMAX, strengt...","{""name""=WHITE, model=MCTS, strength=N...","{whiteGIPF=274877907456, whiteDVONNLa...","{""1""= ...","{""1""=[1010], ""2""=[1013], ""3""=[1000], ...",./agent-1_MCTS_iterations-0-depth-1_a...
15,4990024113595861337,1787828276366,44,"{""name""=WHITE, model=MCTS, strength=N...",MadeTheLastMove,"{""name""=BLACK, model=MINIMAX, strengt...","{""name""=BLACK, model=MINIMAX, strengt...","{""name""=WHITE, model=MCTS, strength=N...","{whiteGIPF=3, whiteDVONNLayer=[209715...","{""1""= ...","{""1""=[1010], ""2""=[639], ""3""=[1000], ""...",./agent-1_MCTS_iterations-0-depth-1_a...
27,-5775348445195429291,1787828276366,50,"{""name""=WHITE, model=MCTS, strength=N...",MadeTheLastMove,"{""name""=BLACK, model=MINIMAX, strengt...","{""name""=BLACK, model=MINIMAX, strengt...","{""name""=WHITE, model=MCTS, strength=N...","{whiteGIPF=268435714, whiteDVONNLayer...","{""1""= ...","{""1""=[1010], ""2""=[741], ""3""=[1000], ""...",./agent-1_MCTS_iterations-0-depth-1_a...

In [14]:
winner.count()

3084

In [12]:
val wins = winner.select {
	winCondition and winner.except { piecesInReserve and capturedPieces }
}.valueCounts()

In [13]:
wins

winCondition,winner,,,,,,,,,,count
,"""name""",model,strength,timeControl,timeDuration,useRAVE,enableFPU,enablePW,iterations,depth,
MadeTheLastMove,BLACK,MCTS,NULL,true,PT1S,false,false,false,0,1,1158
MadeTheLastMove,WHITE,MCTS,NULL,true,PT1S,false,false,false,0,1,1139
CapturedAllGIPFPieces,WHITE,MCTS,NULL,true,PT1S,false,false,false,0,1,314
CapturedAllGIPFPieces,BLACK,MCTS,NULL,true,PT1S,false,false,false,0,1,300
CapturedAllGIPFPieces,WHITE,MINIMAX,NULL,true,PT1S,false,false,false,0,1,79
CapturedAllGIPFPieces,BLACK,MINIMAX,NULL,true,PT1S,false,false,false,0,1,72
MadeTheLastMove,BLACK,MINIMAX,NULL,true,PT1S,false,false,false,0,1,10
MadeTheLastMove,WHITE,MINIMAX,NULL,true,PT1S,false,false,false,0,1,5

In [19]:
winner.select {
	winCondition and winner.`"name"`
}.valueCounts()

winCondition,"""name""",count
MadeTheLastMove,BLACK,1168
MadeTheLastMove,WHITE,1144
CapturedAllGIPFPieces,WHITE,393
CapturedAllGIPFPieces,BLACK,372

In [37]:
val totalGames = 3084.0

In [26]:
totalGames

3084

In [35]:
wins.add("win_percentage") {
	count.div(3084.0).times(100.0)
}

winCondition,winner,,,,,,,,,,count,win_percentage
,"""name""",model,strength,timeControl,timeDuration,useRAVE,enableFPU,enablePW,iterations,depth,,
MadeTheLastMove,BLACK,MCTS,NULL,true,PT1S,false,false,false,0,1,1158,37.548638
MadeTheLastMove,WHITE,MCTS,NULL,true,PT1S,false,false,false,0,1,1139,36.932555
CapturedAllGIPFPieces,WHITE,MCTS,NULL,true,PT1S,false,false,false,0,1,314,10.181582
CapturedAllGIPFPieces,BLACK,MCTS,NULL,true,PT1S,false,false,false,0,1,300,9.727626
CapturedAllGIPFPieces,WHITE,MINIMAX,NULL,true,PT1S,false,false,false,0,1,79,2.561608
CapturedAllGIPFPieces,BLACK,MINIMAX,NULL,true,PT1S,false,false,false,0,1,72,2.334630
MadeTheLastMove,BLACK,MINIMAX,NULL,true,PT1S,false,false,false,0,1,10,0.324254
MadeTheLastMove,WHITE,MINIMAX,NULL,true,PT1S,false,false,false,0,1,5,0.162127

In [36]:
val winning = winner.select {
	winner.select { model and strength }
}.valueCounts()

In [38]:
winning.add("win_percentage") {
	count.div(totalGames) * 100.0
}

model,strength,count,win_percentage
MCTS,NULL,2911,94.390402
MINIMAX,NULL,166,5.382620

In [42]:
winner.groupBy { winner.model }.meanOf { turn }

model,mean
MCTS,72.072140
MINIMAX,66.018072
null,NaN

In [45]:
winner.turn.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,p25,median,p75,max
turn,Long?,3084,131,7,65,79,71.745531,20.017757,14,58.000000,71.000000,83.000000,161

In [44]:
winner.groupBy { winner.model }.stdOf { turn }

model,std
MCTS,19.457142
MINIMAX,27.541808
null,NaN

In [17]:
// 1. Isolate the winner columns (including the unique seed)
val winners = concat.select {
	seed and turn and winner.winCondition and winner.winner.select { model and strength }
}.rename { colsOf<String?>() }.into { "winner_${it.name}" }

// 3. Isolate and rename the next player columns
val nextPlayers = concat.select {
	seed and winner.loser.select { model and strength }
}.rename { colsOf<String?>() }.into { "loser_${it.name}" }

// 4. Join them all together on the 'seed' column
winners
//	.join(currentPlayers, "seed")
	.join(nextPlayers, "seed")
	.remove("seed") // Optional: remove if you don't want seed included in the valueCounts
	.valueCounts()

winner_winCondition,winner_model,winner_strength,loser_model,loser_strength,count
MadeTheLastMove,MINIMAX,GREEDY,MCTS,RANDOM,939
MadeTheLastMove,MCTS,EASY,MCTS,RANDOM,924
MadeTheLastMove,MINIMAX,EASY,MCTS,RANDOM,892
MadeTheLastMove,MCTS,EASY,MINIMAX,GREEDY,660
MadeTheLastMove,MCTS,EASY,MINIMAX,EASY,539
MadeTheLastMove,MINIMAX,EASY,MINIMAX,GREEDY,495
MadeTheLastMove,MINIMAX,GREEDY,MINIMAX,EASY,368
CapturedAllGIPFPieces,MCTS,EASY,MINIMAX,EASY,260
CapturedAllGIPFPieces,MCTS,EASY,MINIMAX,GREEDY,233
MadeTheLastMove,MINIMAX,EASY,MCTS,EASY,182
MadeTheLastMove,MINIMAX,GREEDY,MCTS,EASY,107
CapturedAllGIPFPieces,MINIMAX,EASY,MINIMAX,GREEDY,106
CapturedAllGIPFPieces,MCTS,EASY,MCTS,RANDOM,74
CapturedAllGIPFPieces,MINIMAX,EASY,MCTS,RANDOM,69
MadeTheLastMove,MCTS,RANDOM,MINIMAX,GREEDY,34
CapturedAllGIPFPieces,MINIMAX,GREEDY,MINIMAX,EASY,31
MadeTheLastMove,MCTS,RANDOM,MINIMAX,EASY,30
CapturedAllGIPFPieces,MINIMAX,EASY,MCTS,EASY,19
CapturedAllGIPFPieces,MCTS,RANDOM,MINIMAX,GREEDY,18
CapturedAllGIPFPieces,MCTS,RANDOM,MINIMAX,EASY,9

In [ ]:
mm_e_vs_mcts_e.turn.values().plus(mcts_e_vs_mm_e.turn.values()).average()
mm_e_vs_mcts_e.turn.values().plus(mcts_e_vs_mm_e.turn.values()).max()

In [ ]:
mm_e_vs_mcts_e.turn.values().plus(mcts_e_vs_mm_e.turn.values()).max()

In [18]:
concat.turn.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,p25,median,p75,max
turn,Int,6000,138,0,55,158,68.961667,19.957962,20,55.000000,66.000000,80.000000,240

In [35]:
concat.select { turn and winner.winner.model and winner.winner.strength and winner.loser.model.rename and winner.loser.strength } .groupBy { "model" and "strength" }.mean()

java.lang.IllegalStateException: Column not found: loserModel

In [23]:
concat.turn.mean() + 1.96 * concat.turn.std().div(sqrt(6000.0))

69.46667278456603

In [42]:
// 1. Isolate the winner columns (including the unique seed)
val winners = concat.select {
	seed and turn and winner.winner.select { model and strength }
}.rename { colsOf<String?>() }.into { "winner_${it.name}" }

// 3. Isolate and rename the next player columns
val nextPlayers = concat.select {
	seed and winner.loser.select { model and strength }
}.rename { colsOf<String?>() }.into { "loser_${it.name}" }

// 4. Join them all together on the 'seed' column
winners
//	.join(currentPlayers, "seed")
	.join(nextPlayers, "seed")
	.remove("seed") // Optional: remove if you don't want seed included in the valueCounts
	.groupBy { "winner_model" and "winner_strength" and "loser_model" and "loser_strength" }.mean()

winner_model,winner_strength,loser_model,loser_strength,turn
MCTS,EASY,MCTS,RANDOM,55.397796
MCTS,RANDOM,MCTS,EASY,47.500000
MINIMAX,EASY,MCTS,EASY,79.507463
MCTS,EASY,MINIMAX,EASY,79.117647
MCTS,EASY,MINIMAX,GREEDY,72.640538
MINIMAX,GREEDY,MCTS,EASY,75.719626
MINIMAX,EASY,MCTS,RANDOM,67.431842
MCTS,RANDOM,MINIMAX,EASY,83.256410
MCTS,RANDOM,MINIMAX,GREEDY,78.538462
MINIMAX,GREEDY,MCTS,RANDOM,69.638186
MINIMAX,GREEDY,MINIMAX,EASY,69.348371
MINIMAX,EASY,MINIMAX,GREEDY,67.224626

In [17]:
// Assuming `gamesDf` is your DataFrame<SearchInfo>
val turnDurationsLong = mcts_e_vs_mcts_e
	.select {
		seed and gameId and
				gameState.turnDuration
	}
	// Step 1: Unpack the nested gameState.turnDuration object
	.flatten()

turnDurationsLong

In [14]:
// Extract and unpivot turn search info
val turnSearchInfoLong = mcts_e_vs_mcts_e
	.select {
//		gameId and
				gameState.turnSearchInfo
	}
	.flatten()
//	.unfold("1")
//	.convert("turnNumber").toInt()
//	// Step 1: Explode List<DataFrame<*>> so each row holds a single DataFrame<*>
//	.explode("searchFramesList")
//	.rename("searchFramesList").into("searchData")
//	// Step 2: Unpack or concatenate the search data frame into tabular columns
//	.flatten()
//	.sortBy { gameId and "turnNumber" }

turnSearchInfoLong