In [116]:
%use dataframe
// %use lets-plot
// %use kandy
// %use plotly
import kotlinx.serialization.json.Json

In [117]:
val dir = "/Users/darronporter/Downloads/Dissertation/code/output/results/aws_results_2026-08-15"

// MCTS Easy as Agent 1
val mcts_easy_vs_mcts_random_records = "$dir/agent-1_MCTS_EASY_agent-2_MCTS_RANDOM_games_record.json"
val mcts_easy_vs_minimax_easy_records = "$dir/agent-1_MCTS_EASY_agent-2_MINIMAX_EASY_games_record.json"
val mcts_easy_vs_minimax_greedy_records = "$dir/agent-1_MCTS_EASY_agent-2_MINIMAX_GREEDY_games_record.json"

// MCTS Random as Agent 1
val mcts_random_vs_mcts_easy_records = "$dir/agent-1_MCTS_RANDOM_agent-2_MCTS_EASY_games_record.json"
val mcts_random_vs_minimax_easy_records = "$dir/agent-1_MCTS_RANDOM_agent-2_MINIMAX_EASY_games_record.json"
val mcts_random_vs_minimax_greedy_records = "$dir/agent-1_MCTS_RANDOM_agent-2_MINIMAX_GREEDY_games_record.json"

// Minimax Easy as Agent 1
val minimax_easy_vs_mcts_easy_records = "$dir/agent-1_MINIMAX_EASY_agent-2_MCTS_EASY_games_record.json"
val minimax_easy_vs_mcts_random_records = "$dir/agent-1_MINIMAX_EASY_agent-2_MCTS_RANDOM_games_record.json"
val minimax_easy_vs_minimax_greedy_records = "$dir/agent-1_MINIMAX_EASY_agent-2_MINIMAX_GREEDY_games_record.json"

// Minimax Greedy as Agent 1
val minimax_greedy_vs_mcts_easy_records = "$dir/agent-1_MINIMAX_GREEDY_agent-2_MCTS_EASY_games_record.json"
val minimax_greedy_vs_mcts_random_records = "$dir/agent-1_MINIMAX_GREEDY_agent-2_MCTS_RANDOM_games_record.json"
val minimax_greedy_vs_minimax_easy_records = "$dir/agent-1_MINIMAX_GREEDY_agent-2_MINIMAX_EASY_games_record.json"

In [118]:
val mcts_e_vs_mcts_r = DataFrame.readJson(mcts_easy_vs_mcts_random_records)
val mcts_e_vs_mm_e = DataFrame.readJson(mcts_easy_vs_minimax_easy_records)
val mcts_e_vs_mm_g = DataFrame.readJson(mcts_easy_vs_minimax_greedy_records)
val mcts_r_vs_mcts_e = DataFrame.readJson(mcts_random_vs_mcts_easy_records)
val mcts_r_vs_mm_e = DataFrame.readJson(mcts_random_vs_minimax_easy_records)
val mcts_r_vs_mm_g = DataFrame.readJson(mcts_random_vs_minimax_greedy_records)
val mm_e_vs_mcts_e = DataFrame.readJson(minimax_easy_vs_mcts_easy_records)
val mm_e_vs_mcts_r = DataFrame.readJson(minimax_easy_vs_mcts_random_records)
val mm_e_vs_mm_g = DataFrame.readJson(minimax_easy_vs_minimax_greedy_records)
val mm_g_vs_mcts_e = DataFrame.readJson(minimax_greedy_vs_mcts_easy_records)
val mm_g_vs_mcts_r = DataFrame.readJson(minimax_greedy_vs_mcts_random_records)
val mm_g_vs_mm_e = DataFrame.readJson(minimax_greedy_vs_minimax_easy_records)

CompositeException in converters (fields callbacks): 2 exceptions occurred.
CompositeException in converters (fields callbacks): 2 exceptions occurred.
-------------------------------
Exception 0:
org.jetbrains.kotlinx.jupyter.exceptions.ReplCompilerException: Line_302.jupyter.kts (1:1 - 2:27) 'public abstract val gameState: Line_22_jupyter.GameState defined in Line_302_jupyter._DataFrameType10' clashes with 'public abstract val gameState: Line_184_jupyter.Matrx.GameState defined in Line_184_jupyter.Matrx': property types are incompatible
at Cell In[0], line 5, column 17: No cast needed
	at org.jetbrains.kotlinx.jupyter.compiler.CompiledScriptCache.deserializeResult-wUyqLnw(CompiledScriptCache.kt:36)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.internalEvaluator$lambda$0(ReplForJupyterImpl.kt:347)
	at org.jetbrains.kotlinx.jupyter.repl.impl.InternalEvaluatorImpl.eval(InternalEvaluatorImpl.kt:129)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl.execute_W38Nk0s$lambda$0$1(CellExecutorImpl.kt:95)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.withHost(ReplForJupyterImpl.kt:729)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl.execute-W38Nk0s(CellExecutorImpl.kt:93)
	at org.jetbrains.kotlinx.jupyter.repl.execution.CellExecutor.execute-W38Nk0s$default(CellExecutor.kt:14)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl$ExecutionContext.execute(CellExecutorImpl.kt:306)
	at org.jetbrains.kotlinx.dataframe.jupyter.ExecuteKt.execute(execute.kt:15)
	at org.jetbrains.kotlinx.dataframe.jupyter.ExecuteKt.execute(execute.kt:32)
	at org.jetbrains.kotlinx.dataframe.jupyter.Integration.updateAnyFrameVariable(Integration.kt:138)
	at org.jetbrains.kotlinx.dataframe.jupyter.Integration.access$updateAnyFrameVariable(Integration.kt:63)
	at org.jetbrains.kotlinx.dataframe.jupyter.Integration$onLoaded$5.execution$lambda$0(Integration.kt:330)
	at org.jetbrains.kotlinx.jupyter.api.libraries.FieldHandlerFactory.createUpdateExecution$lambda$0(FieldHandlerFactory.kt:42)
	at org.jetbrains.kotlinx.jupyter.codegen.FieldsProcessorImplKt.executeEx(FieldsProcessorImpl.kt:102)
	at org.jetbrains.kotlinx.jupyter.codegen.FieldsProcessorImplKt.access$executeEx(FieldsProcessorImpl.kt:1)
	at org.jetbrains.kotlinx.jupyter.codegen.FieldsProcessorImpl.process(FieldsProcessorImpl.kt:51)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl.execute_W38Nk0s$lambda$0$2(CellExecutorImpl.kt:114)
	at org.jetbrains.kotlinx.jupyter.config.LoggingKt.catchAll(Logging.kt:33)
	at org.jetbrains.kotlinx.jupyter.config.LoggingKt.catchAll$default(Logging.kt:27)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl.execute-W38Nk0s(CellExecutorImpl.kt:113)
	at org.jetbrains.kotlinx.jupyter.repl.execution.CellExecutor.execute-W38Nk0s$default(CellExecutor.kt:14)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.evaluateUserCode-wNURfNM(ReplForJupyterImpl.kt:578)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.evalExImpl(ReplForJupyterImpl.kt:458)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.evalEx$lambda$0(ReplForJupyterImpl.kt:452)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.withEvalContext(ReplForJupyterImpl.kt:441)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.evalEx(ReplForJupyterImpl.kt:451)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.processExecuteRequest$lambda$0$0$0(IdeCompatibleMessageRequestProcessor.kt:179)
	at org.jetbrains.kotlinx.jupyter.streams.BlockingSubstitutionEngine.withDataSubstitution(SubstitutionEngine.kt:124)
	at org.jetbrains.kotlinx.jupyter.streams.StreamSubstitutionManager.withSubstitutedStreams(StreamSubstitutionManager.kt:118)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.withForkedIn(IdeCompatibleMessageRequestProcessor.kt:373)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.evalWithIO$lambda$0$0(IdeCompatibleMessageRequestProcessor.kt:386)
	at org.jetbrains.kotlinx.jupyter.streams.BlockingSubstitutionEngine.withDataSubstitution(SubstitutionEngine.kt:124)
	at org.jetbrains.kotlinx.jupyter.streams.StreamSubstitutionManager.withSubstitutedStreams(StreamSubstitutionManager.kt:118)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.withForkedErr(IdeCompatibleMessageRequestProcessor.kt:363)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.evalWithIO$lambda$0(IdeCompatibleMessageRequestProcessor.kt:385)
	at org.jetbrains.kotlinx.jupyter.streams.BlockingSubstitutionEngine.withDataSubstitution(SubstitutionEngine.kt:124)
	at org.jetbrains.kotlinx.jupyter.streams.StreamSubstitutionManager.withSubstitutedStreams(StreamSubstitutionManager.kt:118)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.withForkedOut(IdeCompatibleMessageRequestProcessor.kt:356)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.evalWithIO(IdeCompatibleMessageRequestProcessor.kt:384)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.processExecuteRequest$lambda$0$0(IdeCompatibleMessageRequestProcessor.kt:178)
	at org.jetbrains.kotlinx.jupyter.execution.JupyterExecutorImpl$Task.execute(JupyterExecutorImpl.kt:41)
	at org.jetbrains.kotlinx.jupyter.execution.JupyterExecutorImpl.executorThread$lambda$0(JupyterExecutorImpl.kt:81)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
-------------------------------
Exception 1:
org.jetbrains.kotlinx.jupyter.exceptions.ReplCompilerException: Line_303.jupyter.kts (1:1 - 2:27) 'public abstract val gameState: Line_22_jupyter.GameState defined in Line_303_jupyter._DataFrameType10' clashes with 'public abstract val gameState: Line_184_jupyter.Matrx.GameState defined in Line_184_jupyter.Matrx': property types are incompatible
at Cell In[0], line 5, column 17: No cast needed
	at org.jetbrains.kotlinx.jupyter.compiler.CompiledScriptCache.deserializeResult-wUyqLnw(CompiledScriptCache.kt:36)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.internalEvaluator$lambda$0(ReplForJupyterImpl.kt:347)
	at org.jetbrains.kotlinx.jupyter.repl.impl.InternalEvaluatorImpl.eval(InternalEvaluatorImpl.kt:129)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl.execute_W38Nk0s$lambda$0$1(CellExecutorImpl.kt:95)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.withHost(ReplForJupyterImpl.kt:729)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl.execute-W38Nk0s(CellExecutorImpl.kt:93)
	at org.jetbrains.kotlinx.jupyter.repl.execution.CellExecutor.execute-W38Nk0s$default(CellExecutor.kt:14)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl$ExecutionContext.execute(CellExecutorImpl.kt:306)
	at org.jetbrains.kotlinx.dataframe.jupyter.ExecuteKt.execute(execute.kt:15)
	at org.jetbrains.kotlinx.dataframe.jupyter.ExecuteKt.execute(execute.kt:32)
	at org.jetbrains.kotlinx.dataframe.jupyter.Integration.updateAnyFrameVariable(Integration.kt:138)
	at org.jetbrains.kotlinx.dataframe.jupyter.Integration.access$updateAnyFrameVariable(Integration.kt:63)
	at org.jetbrains.kotlinx.dataframe.jupyter.Integration$onLoaded$5.execution$lambda$0(Integration.kt:330)
	at org.jetbrains.kotlinx.jupyter.api.libraries.FieldHandlerFactory.createUpdateExecution$lambda$0(FieldHandlerFactory.kt:42)
	at org.jetbrains.kotlinx.jupyter.codegen.FieldsProcessorImplKt.executeEx(FieldsProcessorImpl.kt:102)
	at org.jetbrains.kotlinx.jupyter.codegen.FieldsProcessorImplKt.access$executeEx(FieldsProcessorImpl.kt:1)
	at org.jetbrains.kotlinx.jupyter.codegen.FieldsProcessorImpl.process(FieldsProcessorImpl.kt:51)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl.execute_W38Nk0s$lambda$0$2(CellExecutorImpl.kt:114)
	at org.jetbrains.kotlinx.jupyter.config.LoggingKt.catchAll(Logging.kt:33)
	at org.jetbrains.kotlinx.jupyter.config.LoggingKt.catchAll$default(Logging.kt:27)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl.execute-W38Nk0s(CellExecutorImpl.kt:113)
	at org.jetbrains.kotlinx.jupyter.repl.execution.CellExecutor.execute-W38Nk0s$default(CellExecutor.kt:14)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.evaluateUserCode-wNURfNM(ReplForJupyterImpl.kt:578)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.evalExImpl(ReplForJupyterImpl.kt:458)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.evalEx$lambda$0(ReplForJupyterImpl.kt:452)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.withEvalContext(ReplForJupyterImpl.kt:441)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.evalEx(ReplForJupyterImpl.kt:451)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.processExecuteRequest$lambda$0$0$0(IdeCompatibleMessageRequestProcessor.kt:179)
	at org.jetbrains.kotlinx.jupyter.streams.BlockingSubstitutionEngine.withDataSubstitution(SubstitutionEngine.kt:124)
	at org.jetbrains.kotlinx.jupyter.streams.StreamSubstitutionManager.withSubstitutedStreams(StreamSubstitutionManager.kt:118)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.withForkedIn(IdeCompatibleMessageRequestProcessor.kt:373)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.evalWithIO$lambda$0$0(IdeCompatibleMessageRequestProcessor.kt:386)
	at org.jetbrains.kotlinx.jupyter.streams.BlockingSubstitutionEngine.withDataSubstitution(SubstitutionEngine.kt:124)
	at org.jetbrains.kotlinx.jupyter.streams.StreamSubstitutionManager.withSubstitutedStreams(StreamSubstitutionManager.kt:118)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.withForkedErr(IdeCompatibleMessageRequestProcessor.kt:363)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.evalWithIO$lambda$0(IdeCompatibleMessageRequestProcessor.kt:385)
	at org.jetbrains.kotlinx.jupyter.streams.BlockingSubstitutionEngine.withDataSubstitution(SubstitutionEngine.kt:124)
	at org.jetbrains.kotlinx.jupyter.streams.StreamSubstitutionManager.withSubstitutedStreams(StreamSubstitutionManager.kt:118)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.withForkedOut(IdeCompatibleMessageRequestProcessor.kt:356)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.evalWithIO(IdeCompatibleMessageRequestProcessor.kt:384)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.processExecuteRequest$lambda$0$0(IdeCompatibleMessageRequestProcessor.kt:178)
	at org.jetbrains.kotlinx.jupyter.execution.JupyterExecutorImpl$Task.execute(JupyterExecutorImpl.kt:41)
	at org.jetbrains.kotlinx.jupyter.execution.JupyterExecutorImpl.executorThread$lambda$0(JupyterExecutorImpl.kt:81)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
-------------------------------

In [119]:
val dataframes = listOf<DataFrame<*>>(
	mcts_e_vs_mcts_r, mcts_e_vs_mm_e, mcts_e_vs_mm_g, mcts_r_vs_mcts_e, mcts_r_vs_mm_e, mcts_r_vs_mm_g, mm_e_vs_mcts_e, mm_e_vs_mcts_r, mm_e_vs_mm_g, mm_g_vs_mcts_e, mm_g_vs_mcts_r, mm_g_vs_mm_e
)

In [82]:
//mcts_e_vs_mcts_r.generateInterfaces("Matrx")

@DataSchema
interface Matrx {
    val gameId: Int
    val gameState: GameState
    val seed: Long
    val timestamp: Long
    val turn: Int
    val winner: Winner

    @DataSchema(isOpen = false)
    interface Bitboard {
        val blackDVONNLayer: List<Long>
        val blackGIPF: Long?
        val blackPUNCTLayer: List<Long>
        val blackPotentials: Long
        val blackTAMSK: Long?
        val blackYINSH: Long?
        val blackZERTZ: Long?
        val whiteDVONNLayer: List<Long>
        val whiteGIPF: Long?
        val whitePUNCTLayer: List<Long>
        val whitePotentials: Long?
        val whiteTAMSK: Long?
        val whiteYINSH: Long?
        val whiteZERTZ: Long?
    }

    @DataSchema(isOpen = false)
    interface CurrentPlayer {
        val capturedPieces: List<Int>
        val model: String
        val name: String
        val piecesInReserve: List<Int>
        val strength: String
        val timeControl: Boolean
        val useRAVE: Boolean
    }

    @DataSchema(isOpen = false)
    interface GameState {
        val bitboard: Bitboard
        val currentPlayer: CurrentPlayer
        val nextPlayer: CurrentPlayer
    }

    @DataSchema(isOpen = false)
    interface Winner {
        val first: CurrentPlayer
        val second: String
    }
}

In [120]:
@DataSchema
interface Matrx {
	val gameId: Int
	val gameState: GameState
	val seed: Long
	val timestamp: Long
	val turn: Int
	val winner: Winner

	@DataSchema(isOpen = false)
	interface Bitboard {
		val blackDVONNLayer: List<Long>
		val blackGIPF: Long?
		val blackPUNCTLayer: List<Long>
		val blackPotentials: Long
		val blackTAMSK: Long?
		val blackYINSH: Long?
		val blackZERTZ: Long?
		val whiteDVONNLayer: List<Long>
		val whiteGIPF: Long?
		val whitePUNCTLayer: List<Long>
		val whitePotentials: Long?
		val whiteTAMSK: Long?
		val whiteYINSH: Long?
		val whiteZERTZ: Long?
	}

	@DataSchema(isOpen = false)
	interface CurrentPlayer {
		val capturedPieces: List<Int>
		val model: String
		val name: String
		val piecesInReserve: List<Int>
		val strength: String
		val timeControl: Boolean
		val useRAVE: Boolean
	}

	@DataSchema(isOpen = false)
	interface GameState {
		val bitboard: Bitboard
		val currentPlayer: CurrentPlayer
		val nextPlayer: CurrentPlayer
	}

	@DataSchema(isOpen = false)
	interface Winner {
		val first: CurrentPlayer
		val second: String
	}
}

In [121]:
dataframes.map { it.head(5)  }

[   gameId                 seed     timestamp turn                                   winner                                gameState
 0      2  4354684877700342270 1786749180391   53 { first:{ name:BLACK, model:MCTS, str... { currentPlayer:{ name:WHITE, model:M...
 1     14 -6410687681057124110 1786749180391   55 { first:{ name:BLACK, model:MCTS, str... { currentPlayer:{ name:WHITE, model:M...
 2      4  8709371542232181120 1786749180391   61 { first:{ name:BLACK, model:MCTS, str... { currentPlayer:{ name:WHITE, model:M...
 3      9 -8074032580152621719 1786749180391   64 { first:{ name:WHITE, model:MCTS, str... { currentPlayer:{ name:BLACK, model:M...
 4      5  1663342562724328893 1786749180391   64 { first:{ name:WHITE, model:MCTS, str... { currentPlayer:{ name:BLACK, model:M...
,    gameId                 seed     timestamp turn                                   winner                                gameState
 0      8 -1028003325813312814 1786751079054   79 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 1     14 -6410687681055220900 1786751079054   85 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 2      4  8709371542229754414 1786751079054   56 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 3      7  6018029227106940649 1786751079054   81 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 4      5  1663342562722561555 1786751079054   97 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
,    gameId                 seed     timestamp turn                                   winner                                gameState
 0     12  7681369728193428762 1786741370361   47 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 1      1 -7046031041124904461 1786741370361   69 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 2     11 -3719345091062073087 1786741370361   61 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 3      7  6018029227098294645 1786741370361   71 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 4      3 -2691344376612070951 1786741370361   79 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
,    gameId                 seed     timestamp turn                                   winner                                gameState
 0      7  6018029227106040057 1786750147709   63 { first:{ name:BLACK, model:MCTS, str... { currentPlayer:{ name:WHITE, model:M...
 1      5  1663342562723753987 1786750147709   66 { first:{ name:WHITE, model:MCTS, str... { currentPlayer:{ name:BLACK, model:M...
 2      8 -1028003325816570686 1786750147709   61 { first:{ name:BLACK, model:MCTS, str... { currentPlayer:{ name:WHITE, model:M...
 3     14 -6410687681058482868 1786750147709   56 { first:{ name:WHITE, model:MCTS, str... { currentPlayer:{ name:BLACK, model:M...
 4      3 -2691344376620849067 1786750147709   72 { first:{ name:WHITE, model:MCTS, str... { currentPlayer:{ name:BLACK, model:M...
,    gameId                 seed     timestamp turn                                   winner                                gameState
 0     12  7681369728212091290 1786739462521   39 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 1      6 -5382685592217290472 1786739462521   43 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 2      2  4354684877756197196 1786739462521   86 { first:{ name:WHITE, model:MCTS, str... { currentPlayer:{ name:BLACK, model:M...
 3      5  1663342562700492047 1786739462521   57 { first:{ name:WHITE, model:MCTS, str... { currentPlayer:{ name:BLACK, model:M...
 4     11 -3719345091068050047 1786739462521   55 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
,    gameId                 seed     timestamp turn                                   winner                                gameState
 0     10  3326683063783514254 1786739374191   39 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 1      6 -5382685592217071582 1786739374191   47 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 2     16 -2056005139741738740 1786739374191   51 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 3     11 -3719345091068531525 1786739374191   47 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 4     15  4990024114621807975 1786739374191   49 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
,    gameId                 seed     timestamp turn                                   winner                                gameState
 0     10  3326683063802065788 1786753723329   22 { first:{ name:BLACK, model:MCTS, str... { currentPlayer:{ name:WHITE, model:M...
 1     12  7681369728198114130 1786753723329   29 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 2      7  6018029227110780733 1786753723329   76 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 3      6 -5382685592231558192 1786753723329   92 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 4     11 -3719345091049849015 1786753723329   83 { first:{ name:BLACK, model:MCTS, str... { currentPlayer:{ name:WHITE, model:M...
,    gameId                 seed     timestamp turn                                   winner                                gameState
 0     11 -3719345091060764165 1786740581679   88 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 1      7  6018029227096457615 1786740581679   60 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 2      5  1663342562716273013 1786740581679   44 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 3      6 -5382685592226673310 1786740581679   71 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 4     18  2298681524661591142 1786740581679   76 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
,    gameId                 seed     timestamp turn                                   winner                                gameState
 0      9 -8074032580139430215 1786744508951   21 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 1     16 -2056005139715435692 1786744508951   75 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 2      8 -1028003325828238676 1786744508951   77 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 3     13   635341573316271893 1786744508951   79 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 4      1 -7046031041130140143 1786744508951   76 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
,    gameId                 seed     timestamp turn                                   winner                                gameState
 0      3 -2691344376609771794 1786743266020   54 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 1      2  4354684877709665019 1786743266020   72 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 2     14 -6410687681065364489 1786743266020   74 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 3      4  8709371542223153797 1786743266020   84 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 4     13   635341573323413440 1786743266020   68 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
,    gameId                 seed     timestamp turn                                   winner                                gameState
 0     12  7681369728212405995 1786739416618   50 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 1      3 -2691344376673031640 1786739416618   58 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 2     16 -2056005139741794489 1786739416618   52 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 3      5  1663342562699883134 1786739416618   95 { first:{ name:BLACK, model:MCTS, str... { currentPlayer:{ name:WHITE, model:M...
 4      8 -1028003325768614209 1786739416618   76 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
,    gameId                 seed     timestamp turn                                   winner                                gameState
 0      8 -1028003325827427504 1786747368459   62 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 1      3 -2691344376613943353 1786747368459   90 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 2      4  8709371542227174316 1786747368459   55 { first:{ name:BLACK, model:MINIMAX, ... { currentPlayer:{ name:WHITE, model:M...
 3      2  4354684877713820626 1786747368459  106 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
 4     16 -2056005139716181336 1786747368459  124 { first:{ name:WHITE, model:MINIMAX, ... { currentPlayer:{ name:BLACK, model:M...
]

In [39]:
mcts_e_vs_mcts_r

In [122]:
mcts_e_vs_mcts_r.winner.first.name.valueCounts()

name,count
BLACK,336
WHITE,164

In [21]:
mcts_e_vs_mcts_r.winner.second.valueCounts()

second,count
MadeTheLastMove,893
CapturedAllGIPFPieces,107

In [123]:
mcts_r_vs_mcts_e.winner.first.name.valueCounts()

name,count
WHITE,340
BLACK,160

In [124]:
mcts_r_vs_mcts_e.winner.second.valueCounts()

second,count
MadeTheLastMove,469
CapturedAllGIPFPieces,31

In [125]:
dataframes.map { it["winner"]["first"]["strength"].valueCounts() }

[   strength count
 0   RANDOM   336
 1     EASY   164
,    strength count
 0     EASY   500
,    strength count
 0   GREEDY   572
 1     EASY    28
,    strength count
 0   RANDOM   340
 1     EASY   160
,    strength count
 0     EASY   458
 1   RANDOM    42
,    strength count
 0   GREEDY   484
 1   RANDOM    16
,    strength count
 0     EASY   500
,    strength count
 0     EASY   444
 1   RANDOM    56
,    strength count
 0   GREEDY   315
 1     EASY   185
,    strength count
 0   GREEDY   472
 1     EASY    28
,    strength count
 0   GREEDY   482
 1   RANDOM    18
,    strength count
 0   GREEDY   279
 1     EASY   221
]

In [126]:
dataframes.forEach { println(it.getColumnGroup("winner").getColumnGroup("first").select { cols(0..2) }.valueCounts()) }

    name model strength count
 0 BLACK  MCTS   RANDOM   336
 1 WHITE  MCTS     EASY   164

    name   model strength count
 0 BLACK MINIMAX     EASY   467
 1 WHITE    MCTS     EASY    33

    name   model strength count
 0 BLACK MINIMAX   GREEDY   572
 1 WHITE    MCTS     EASY    28

    name model strength count
 0 WHITE  MCTS   RANDOM   340
 1 BLACK  MCTS     EASY   160

    name   model strength count
 0 BLACK MINIMAX     EASY   458
 1 WHITE    MCTS   RANDOM    42

    name   model strength count
 0 BLACK MINIMAX   GREEDY   484
 1 WHITE    MCTS   RANDOM    16

    name   model strength count
 0 WHITE MINIMAX     EASY   452
 1 BLACK    MCTS     EASY    48

    name   model strength count
 0 WHITE MINIMAX     EASY   444
 1 BLACK    MCTS   RANDOM    56

    name   model strength count
 0 BLACK MINIMAX   GREEDY   315
 1 WHITE MINIMAX     EASY   185

    name   model strength count
 0 WHITE MINIMAX   GREEDY   472
 1 BLACK    MCTS     EASY    28

    name   model strength count
 0 WHITE MINIMAX   GREEDY   482
 1 BLACK    MCTS   RANDOM    18

    name   model strength count
 0 WHITE MINIMAX   GREEDY   279
 1 BLACK MINIMAX     EASY   221

In [127]:
mcts_e_vs_mcts_r.groupBy { winner.second }.aggregate {
	it.getColumnGroup("winner").getColumnGroup("first").select { cols(0..2) }.valueCounts()
}.toStandaloneHtml()

In [151]:
var concat = dataframes.concat().cast<Matrx>()

In [129]:
concat.select {
	winner.second and winner.first.cols(0..2)
}.valueCounts()

second,name,model,strength,count
MadeTheLastMove,BLACK,MINIMAX,GREEDY,1319
MadeTheLastMove,WHITE,MINIMAX,GREEDY,1184
MadeTheLastMove,BLACK,MINIMAX,EASY,921
MadeTheLastMove,WHITE,MINIMAX,EASY,848
MadeTheLastMove,BLACK,MCTS,RANDOM,361
MadeTheLastMove,WHITE,MCTS,RANDOM,339
CapturedAllGIPFPieces,WHITE,MINIMAX,EASY,233
CapturedAllGIPFPieces,BLACK,MINIMAX,EASY,225
MadeTheLastMove,BLACK,MCTS,EASY,211
MadeTheLastMove,WHITE,MCTS,EASY,198
CapturedAllGIPFPieces,WHITE,MCTS,RANDOM,59
CapturedAllGIPFPieces,BLACK,MINIMAX,GREEDY,52
CapturedAllGIPFPieces,BLACK,MCTS,RANDOM,49
CapturedAllGIPFPieces,WHITE,MINIMAX,GREEDY,49
CapturedAllGIPFPieces,WHITE,MCTS,EASY,27
CapturedAllGIPFPieces,BLACK,MCTS,EASY,25

In [130]:
dataframes.map { it.count() }

[500, 500, 600, 500, 500, 500, 500, 500, 500, 500, 500, 500]

In [131]:
dataframes.map { it.count() }.sum()

6100

In [132]:
val totalGames = 3000.0

In [133]:
val wins = concat.select {
	winner.second and winner.first.select { model and strength }
}.valueCounts()

In [134]:
wins.add("win_percentage") {
	(count / totalGames) * 100.0
}

second,model,strength,count,win_percentage
MadeTheLastMove,MINIMAX,GREEDY,2503,83.433333
MadeTheLastMove,MINIMAX,EASY,1769,58.966667
MadeTheLastMove,MCTS,RANDOM,700,23.333333
CapturedAllGIPFPieces,MINIMAX,EASY,458,15.266667
MadeTheLastMove,MCTS,EASY,409,13.633333
CapturedAllGIPFPieces,MCTS,RANDOM,108,3.600000
CapturedAllGIPFPieces,MINIMAX,GREEDY,101,3.366667
CapturedAllGIPFPieces,MCTS,EASY,52,1.733333

In [135]:
val winning = concat.select {
	winner.first.select { model and strength }
}.valueCounts()

In [136]:
winning.add("win_percentage") {
	(count / totalGames) * 100.0
}

model,strength,count,win_percentage
MINIMAX,GREEDY,2604,86.800000
MINIMAX,EASY,2227,74.233333
MCTS,RANDOM,808,26.933333
MCTS,EASY,461,15.366667

In [158]:
// 1. Isolate the winner columns (including the unique seed)
val winners = concat.select {
	seed and winner.second and winner.first.cols(0..2)
}.rename { colsOf<String>() }.into { "winner_${it.name}" }

// 2. Isolate and rename the current player columns
val currentPlayers = concat.select {
	seed and gameState.currentPlayer.select { name and model and strength }
}.rename { colsOf<String>() }.into { "current_${it.name}" }

// 3. Isolate and rename the next player columns
val nextPlayers = concat.select {
	seed and gameState.nextPlayer.select { name and model and strength }
}.rename { colsOf<String>() }.into { "next_${it.name}" }

// 4. Join them all together on the 'seed' column
winners
	.join(currentPlayers, "seed")
	.join(nextPlayers, "seed")
	.remove("seed") // Optional: remove if you don't want seed included in the valueCounts
	.valueCounts()

winner_second,winner_name,winner_model,winner_strength,current_name,current_model,current_strength,next_name,next_model,next_strength,count
MadeTheLastMove,BLACK,MINIMAX,GREEDY,WHITE,MCTS,EASY,BLACK,MINIMAX,GREEDY,537
MadeTheLastMove,BLACK,MINIMAX,GREEDY,WHITE,MCTS,RANDOM,BLACK,MINIMAX,GREEDY,481
MadeTheLastMove,WHITE,MINIMAX,GREEDY,BLACK,MCTS,RANDOM,WHITE,MINIMAX,GREEDY,478
MadeTheLastMove,WHITE,MINIMAX,GREEDY,BLACK,MCTS,EASY,WHITE,MINIMAX,GREEDY,442
MadeTheLastMove,BLACK,MINIMAX,EASY,WHITE,MCTS,RANDOM,BLACK,MINIMAX,EASY,433
MadeTheLastMove,WHITE,MINIMAX,EASY,BLACK,MCTS,RANDOM,WHITE,MINIMAX,EASY,411
MadeTheLastMove,BLACK,MINIMAX,EASY,WHITE,MCTS,EASY,BLACK,MINIMAX,EASY,373
MadeTheLastMove,WHITE,MINIMAX,EASY,BLACK,MCTS,EASY,WHITE,MINIMAX,EASY,351
MadeTheLastMove,BLACK,MCTS,RANDOM,WHITE,MCTS,EASY,BLACK,MCTS,RANDOM,314
MadeTheLastMove,WHITE,MCTS,RANDOM,BLACK,MCTS,EASY,WHITE,MCTS,RANDOM,312
MadeTheLastMove,BLACK,MINIMAX,GREEDY,WHITE,MINIMAX,EASY,BLACK,MINIMAX,GREEDY,301
MadeTheLastMove,WHITE,MINIMAX,GREEDY,BLACK,MINIMAX,EASY,WHITE,MINIMAX,GREEDY,264
MadeTheLastMove,WHITE,MCTS,EASY,BLACK,MCTS,RANDOM,WHITE,MCTS,EASY,160
MadeTheLastMove,BLACK,MCTS,EASY,WHITE,MCTS,RANDOM,BLACK,MCTS,EASY,157
MadeTheLastMove,BLACK,MINIMAX,EASY,WHITE,MINIMAX,GREEDY,BLACK,MINIMAX,EASY,115
CapturedAllGIPFPieces,BLACK,MINIMAX,EASY,WHITE,MINIMAX,GREEDY,BLACK,MINIMAX,EASY,106
CapturedAllGIPFPieces,WHITE,MINIMAX,EASY,BLACK,MCTS,EASY,WHITE,MINIMAX,EASY,101
CapturedAllGIPFPieces,WHITE,MINIMAX,EASY,BLACK,MINIMAX,GREEDY,WHITE,MINIMAX,EASY,99
CapturedAllGIPFPieces,BLACK,MINIMAX,EASY,WHITE,MCTS,EASY,BLACK,MINIMAX,EASY,94
MadeTheLastMove,WHITE,MINIMAX,EASY,BLACK,MINIMAX,GREEDY,WHITE,MINIMAX,EASY,86

In [159]:
// 1. Isolate the winner columns (including the unique seed)
val winners = concat.select {
	seed and winner.first.cols(0..2)
}.rename { colsOf<String>() }.into { "winner_${it.name}" }

// 2. Isolate and rename the current player columns
val currentPlayers = concat.select {
	seed and gameState.currentPlayer.select { name and model and strength }
}.rename { colsOf<String>() }.into { "current_${it.name}" }

// 3. Isolate and rename the next player columns
val nextPlayers = concat.select {
	seed and gameState.nextPlayer.select { name and model and strength }
}.rename { colsOf<String>() }.into { "next_${it.name}" }

// 4. Join them all together on the 'seed' column
winners
	.join(currentPlayers, "seed")
	.join(nextPlayers, "seed")
	.remove("seed") // Optional: remove if you don't want seed included in the valueCounts
	.valueCounts()

winner_name,winner_model,winner_strength,current_name,current_model,current_strength,next_name,next_model,next_strength,count
BLACK,MINIMAX,GREEDY,WHITE,MCTS,EASY,BLACK,MINIMAX,GREEDY,572
BLACK,MINIMAX,GREEDY,WHITE,MCTS,RANDOM,BLACK,MINIMAX,GREEDY,484
WHITE,MINIMAX,GREEDY,BLACK,MCTS,RANDOM,WHITE,MINIMAX,GREEDY,482
WHITE,MINIMAX,GREEDY,BLACK,MCTS,EASY,WHITE,MINIMAX,GREEDY,472
BLACK,MINIMAX,EASY,WHITE,MCTS,EASY,BLACK,MINIMAX,EASY,467
BLACK,MINIMAX,EASY,WHITE,MCTS,RANDOM,BLACK,MINIMAX,EASY,458
WHITE,MINIMAX,EASY,BLACK,MCTS,EASY,WHITE,MINIMAX,EASY,452
WHITE,MINIMAX,EASY,BLACK,MCTS,RANDOM,WHITE,MINIMAX,EASY,444
WHITE,MCTS,RANDOM,BLACK,MCTS,EASY,WHITE,MCTS,RANDOM,340
BLACK,MCTS,RANDOM,WHITE,MCTS,EASY,BLACK,MCTS,RANDOM,336
BLACK,MINIMAX,GREEDY,WHITE,MINIMAX,EASY,BLACK,MINIMAX,GREEDY,315
WHITE,MINIMAX,GREEDY,BLACK,MINIMAX,EASY,WHITE,MINIMAX,GREEDY,279
BLACK,MINIMAX,EASY,WHITE,MINIMAX,GREEDY,BLACK,MINIMAX,EASY,221
WHITE,MINIMAX,EASY,BLACK,MINIMAX,GREEDY,WHITE,MINIMAX,EASY,185
WHITE,MCTS,EASY,BLACK,MCTS,RANDOM,WHITE,MCTS,EASY,164
BLACK,MCTS,EASY,WHITE,MCTS,RANDOM,BLACK,MCTS,EASY,160
BLACK,MCTS,RANDOM,WHITE,MINIMAX,EASY,BLACK,MCTS,RANDOM,56
BLACK,MCTS,EASY,WHITE,MINIMAX,EASY,BLACK,MCTS,EASY,48
WHITE,MCTS,RANDOM,BLACK,MINIMAX,EASY,WHITE,MCTS,RANDOM,42
WHITE,MCTS,EASY,BLACK,MINIMAX,EASY,WHITE,MCTS,EASY,33

In [160]:
// 1. Isolate the winner columns (including the unique seed)
val winners = concat.select {
	seed and winner.first.cols(1..2)
}.rename { colsOf<String>() }.into { "winner_${it.name}" }

// 2. Isolate and rename the current player columns
val currentPlayers = concat.select {
	seed and gameState.currentPlayer.select { model and strength }
}.rename { colsOf<String>() }.into { "current_${it.name}" }

// 3. Isolate and rename the next player columns
val nextPlayers = concat.select {
	seed and gameState.nextPlayer.select { model and strength }
}.rename { colsOf<String>() }.into { "next_${it.name}" }

// 4. Join them all together on the 'seed' column
winners
	.join(currentPlayers, "seed")
	.join(nextPlayers, "seed")
	.remove("seed") // Optional: remove if you don't want seed included in the valueCounts
	.valueCounts()

winner_model,winner_strength,current_model,current_strength,next_model,next_strength,count
MINIMAX,GREEDY,MCTS,EASY,MINIMAX,GREEDY,1044
MINIMAX,GREEDY,MCTS,RANDOM,MINIMAX,GREEDY,966
MINIMAX,EASY,MCTS,EASY,MINIMAX,EASY,919
MINIMAX,EASY,MCTS,RANDOM,MINIMAX,EASY,902
MCTS,RANDOM,MCTS,EASY,MCTS,RANDOM,676
MINIMAX,GREEDY,MINIMAX,EASY,MINIMAX,GREEDY,594
MINIMAX,EASY,MINIMAX,GREEDY,MINIMAX,EASY,406
MCTS,EASY,MCTS,RANDOM,MCTS,EASY,324
MCTS,RANDOM,MINIMAX,EASY,MCTS,RANDOM,98
MCTS,EASY,MINIMAX,EASY,MCTS,EASY,81
MCTS,EASY,MINIMAX,GREEDY,MCTS,EASY,56
MCTS,RANDOM,MINIMAX,GREEDY,MCTS,RANDOM,34