In [1]:
%use dataframe
// %use lets-plot
// %use kandy
// %use plotly
import kotlinx.serialization.json.Json

In [2]:
val dir = "/Users/darronporter/Downloads/Dissertation/code/output/results/gcloud_results-2026-08-17-run_5"

val mctsRave = "/Users/darronporter/Downloads/Dissertation/code/output/results/gcloud-mcts-rave-2026-08-20-run-1/mcts-rave_2026-08-20.json"

// MCTS Easy as Agent 1
val mcts_easy_vs_mcts_random_records = "$dir/agent-1_MCTS_EASY_agent-2_MCTS_RANDOM_games_record.json"
val mcts_easy_vs_minimax_easy_records = "$dir/agent-1_MCTS_EASY_agent-2_MINIMAX_EASY_games_record.json"
val mcts_easy_vs_minimax_greedy_records = "$dir/agent-1_MCTS_EASY_agent-2_MINIMAX_GREEDY_games_record.json"

// MCTS Random as Agent 1
val mcts_random_vs_mcts_easy_records = "$dir/agent-1_MCTS_RANDOM_agent-2_MCTS_EASY_games_record.json"
val mcts_random_vs_minimax_easy_records = "$dir/agent-1_MCTS_RANDOM_agent-2_MINIMAX_EASY_games_record.json"
val mcts_random_vs_minimax_greedy_records = "$dir/agent-1_MCTS_RANDOM_agent-2_MINIMAX_GREEDY_games_record.json"

// Minimax Easy as Agent 1
val minimax_easy_vs_mcts_easy_records = "$dir/agent-1_MINIMAX_EASY_agent-2_MCTS_EASY_games_record.json"
val minimax_easy_vs_mcts_random_records = "$dir/agent-1_MINIMAX_EASY_agent-2_MCTS_RANDOM_games_record.json"
val minimax_easy_vs_minimax_greedy_records = "$dir/agent-1_MINIMAX_EASY_agent-2_MINIMAX_GREEDY_games_record.json"

// Minimax Greedy as Agent 1
val minimax_greedy_vs_mcts_easy_records = "$dir/agent-1_MINIMAX_GREEDY_agent-2_MCTS_EASY_games_record.json"
val minimax_greedy_vs_mcts_random_records = "$dir/agent-1_MINIMAX_GREEDY_agent-2_MCTS_RANDOM_games_record.json"
val minimax_greedy_vs_minimax_easy_records = "$dir/agent-1_MINIMAX_GREEDY_agent-2_MINIMAX_EASY_games_record.json"

In [4]:
val mcts_e_vs_mcts_r = DataFrame.readJson(mcts_easy_vs_mcts_random_records)
val mcts_e_vs_mm_e = DataFrame.readJson(mcts_easy_vs_minimax_easy_records)
val mcts_e_vs_mm_g = DataFrame.readJson(mcts_easy_vs_minimax_greedy_records)
val mcts_r_vs_mcts_e = DataFrame.readJson(mcts_random_vs_mcts_easy_records)
val mcts_r_vs_mm_e = DataFrame.readJson(mcts_random_vs_minimax_easy_records)
val mcts_r_vs_mm_g = DataFrame.readJson(mcts_random_vs_minimax_greedy_records)
val mm_e_vs_mcts_e = DataFrame.readJson(minimax_easy_vs_mcts_easy_records)
val mm_e_vs_mcts_r = DataFrame.readJson(minimax_easy_vs_mcts_random_records)
val mm_e_vs_mm_g = DataFrame.readJson(minimax_easy_vs_minimax_greedy_records)
val mm_g_vs_mcts_e = DataFrame.readJson(minimax_greedy_vs_mcts_easy_records)
val mm_g_vs_mcts_r = DataFrame.readJson(minimax_greedy_vs_mcts_random_records)
val mm_g_vs_mm_e = DataFrame.readJson(minimax_greedy_vs_minimax_easy_records)

In [9]:
@DataSchema
interface MCTSRAVE {
	val seed: Long
	val turn: Int
	val winner: Winner

	@DataSchema(isOpen = false)
	interface Loser {
		val capturedPieces: List<Int>
		val depth: Int
		val enableFPU: Boolean
		val enablePW: Boolean
		val iterations: Int
		val model: String
		val name: String
		val piecesInReserve: List<Int>
		val strength: String
		val timeControl: Boolean
		val useRAVE: Boolean
	}

	@DataSchema(isOpen = false)
	interface Winner {
		val loser: Loser
		val winCondition: String
		val winner: Loser
	}
}

In [10]:
val raveMCTS = DataFrame.readJson(mctsRave).select {
	"seed" and "turn" and "winner"
}.cast<MCTSRAVE>()

The problem is found in one of the loaded libraries: check library converters (fields callbacks)
Error compiling code:
@DataSchema
interface _DataFrameType1 : Line_19_jupyter._DataFrameType, Line_22_jupyter.MCTSRAVE { }


(raveMCTS as org.jetbrains.kotlinx.dataframe.DataFrame<*>).cast<_DataFrameType1>()

Errors:
Line_25.jupyter.kts (1:1 - 2:26) 'public abstract val winner: Line_19_jupyter.Winner defined in Line_25_jupyter._DataFrameType1' clashes with 'public abstract val winner: Line_22_jupyter.MCTSRAVE.Winner defined in Line_22_jupyter.MCTSRAVE': property types are incompatible

org.jetbrains.kotlinx.jupyter.exceptions.ReplLibraryException: The problem is found in one of the loaded libraries: check library converters (fields callbacks)
	at org.jetbrains.kotlinx.jupyter.exceptions.CompositeReplExceptionKt.throwAsLibraryException(CompositeReplException.kt:48)
	at org.jetbrains.kotlinx.jupyter.exceptions.CompositeReplExceptionKt.throwLibraryException(CompositeReplException.kt:54)
	at org.jetbrains.kotlinx.jupyter.codegen.FieldsProcessorImpl.process(FieldsProcessorImpl.kt:72)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl.execute_W38Nk0s$lambda$0$2(CellExecutorImpl.kt:114)
	at org.jetbrains.kotlinx.jupyter.config.LoggingKt.catchAll(Logging.kt:33)
	at org.jetbrains.kotlinx.jupyter.config.LoggingKt.catchAll$default(Logging.kt:27)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl.execute-W38Nk0s(CellExecutorImpl.kt:113)
	at org.jetbrains.kotlinx.jupyter.repl.execution.CellExecutor.execute-W38Nk0s$default(CellExecutor.kt:14)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.evaluateUserCode-wNURfNM(ReplForJupyterImpl.kt:578)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.evalExImpl(ReplForJupyterImpl.kt:458)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.evalEx$lambda$0(ReplForJupyterImpl.kt:452)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.withEvalContext(ReplForJupyterImpl.kt:441)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.evalEx(ReplForJupyterImpl.kt:451)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.processExecuteRequest$lambda$0$0$0(IdeCompatibleMessageRequestProcessor.kt:179)
	at org.jetbrains.kotlinx.jupyter.streams.BlockingSubstitutionEngine.withDataSubstitution(SubstitutionEngine.kt:124)
	at org.jetbrains.kotlinx.jupyter.streams.StreamSubstitutionManager.withSubstitutedStreams(StreamSubstitutionManager.kt:118)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.withForkedIn(IdeCompatibleMessageRequestProcessor.kt:373)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.evalWithIO$lambda$0$0(IdeCompatibleMessageRequestProcessor.kt:386)
	at org.jetbrains.kotlinx.jupyter.streams.BlockingSubstitutionEngine.withDataSubstitution(SubstitutionEngine.kt:124)
	at org.jetbrains.kotlinx.jupyter.streams.StreamSubstitutionManager.withSubstitutedStreams(StreamSubstitutionManager.kt:118)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.withForkedErr(IdeCompatibleMessageRequestProcessor.kt:363)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.evalWithIO$lambda$0(IdeCompatibleMessageRequestProcessor.kt:385)
	at org.jetbrains.kotlinx.jupyter.streams.BlockingSubstitutionEngine.withDataSubstitution(SubstitutionEngine.kt:124)
	at org.jetbrains.kotlinx.jupyter.streams.StreamSubstitutionManager.withSubstitutedStreams(StreamSubstitutionManager.kt:118)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.withForkedOut(IdeCompatibleMessageRequestProcessor.kt:356)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.evalWithIO(IdeCompatibleMessageRequestProcessor.kt:384)
	at org.jetbrains.kotlinx.jupyter.messaging.IdeCompatibleMessageRequestProcessor.processExecuteRequest$lambda$0$0(IdeCompatibleMessageRequestProcessor.kt:178)
	at org.jetbrains.kotlinx.jupyter.execution.JupyterExecutorImpl$Task.execute(JupyterExecutorImpl.kt:41)
	at org.jetbrains.kotlinx.jupyter.execution.JupyterExecutorImpl.executorThread$lambda$0(JupyterExecutorImpl.kt:81)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Caused by: org.jetbrains.kotlinx.jupyter.exceptions.ReplCompilerException: Line_25.jupyter.kts (1:1 - 2:26) 'public abstract val winner: Line_19_jupyter.Winner defined in Line_25_jupyter._DataFrameType1' clashes with 'public abstract val winner: Line_22_jupyter.MCTSRAVE.Winner defined in Line_22_jupyter.MCTSRAVE': property types are incompatible
	at org.jetbrains.kotlinx.jupyter.compiler.CompiledScriptCache.deserializeResult-wUyqLnw(CompiledScriptCache.kt:36)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.internalEvaluator$lambda$0(ReplForJupyterImpl.kt:347)
	at org.jetbrains.kotlinx.jupyter.repl.impl.InternalEvaluatorImpl.eval(InternalEvaluatorImpl.kt:129)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl.execute_W38Nk0s$lambda$0$1(CellExecutorImpl.kt:95)
	at org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.withHost(ReplForJupyterImpl.kt:729)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl.execute-W38Nk0s(CellExecutorImpl.kt:93)
	at org.jetbrains.kotlinx.jupyter.repl.execution.CellExecutor.execute-W38Nk0s$default(CellExecutor.kt:14)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl$ExecutionContext.execute(CellExecutorImpl.kt:306)
	at org.jetbrains.kotlinx.dataframe.jupyter.ExecuteKt.execute(execute.kt:15)
	at org.jetbrains.kotlinx.dataframe.jupyter.ExecuteKt.execute(execute.kt:32)
	at org.jetbrains.kotlinx.dataframe.jupyter.Integration.updateAnyFrameVariable(Integration.kt:138)
	at org.jetbrains.kotlinx.dataframe.jupyter.Integration.access$updateAnyFrameVariable(Integration.kt:63)
	at org.jetbrains.kotlinx.dataframe.jupyter.Integration$onLoaded$5.execution$lambda$0(Integration.kt:330)
	at org.jetbrains.kotlinx.jupyter.api.libraries.FieldHandlerFactory.createUpdateExecution$lambda$0(FieldHandlerFactory.kt:42)
	at org.jetbrains.kotlinx.jupyter.codegen.FieldsProcessorImplKt.executeEx(FieldsProcessorImpl.kt:102)
	at org.jetbrains.kotlinx.jupyter.codegen.FieldsProcessorImplKt.access$executeEx(FieldsProcessorImpl.kt:1)
	at org.jetbrains.kotlinx.jupyter.codegen.FieldsProcessorImpl.process(FieldsProcessorImpl.kt:51)
	... 27 more

In [8]:
raveMCTS.generateInterfaces()

@DataSchema
interface _DataFrameType {
    val seed: Long
    val turn: Int
    val winner: Winner

    @DataSchema(isOpen = false)
    interface Loser {
        val capturedPieces: List<Int>
        val depth: Int
        val enableFPU: Boolean
        val enablePW: Boolean
        val iterations: Int
        val model: String
        val name: String
        val piecesInReserve: List<Int>
        val strength: String
        val timeControl: Boolean
        val useRAVE: Boolean
    }

    @DataSchema(isOpen = false)
    interface Winner {
        val loser: Loser
        val winCondition: String
        val winner: Loser
    }
}

In [5]:
val dataframes =
    listOf<DataFrame<*>>(
        mcts_e_vs_mcts_r,
        mcts_e_vs_mm_e,
        mcts_e_vs_mm_g,
        mcts_r_vs_mcts_e,
        mcts_r_vs_mm_e,
        mcts_r_vs_mm_g,
        mm_e_vs_mcts_e,
        mm_e_vs_mcts_r,
        mm_e_vs_mm_g,
        mm_g_vs_mcts_e,
        mm_g_vs_mcts_r,
        mm_g_vs_mm_e,
    )

In [ ]:
mcts_e_vs_mcts_r.generateInterfaces("Matrx")

In [6]:
@DataSchema
interface Matrx {
	val gameId: Int
	val gameState: GameState
	val seed: Long
	val timestamp: Long
	val turn: Int
	val winner: Winner

	@DataSchema(isOpen = false)
	interface Bitboard {
		val blackDVONNLayer: List<Long>
		val blackGIPF: Long?
		val blackPUNCTLayer: List<Long>
		val blackPotentials: Long
		val blackTAMSK: Long?
		val blackYINSH: Long?
		val blackZERTZ: Long?
		val whiteDVONNLayer: List<Long>
		val whiteGIPF: Long?
		val whitePUNCTLayer: List<Long>
		val whitePotentials: Long
		val whiteTAMSK: Long?
		val whiteYINSH: Long?
		val whiteZERTZ: Long?
	}

	@DataSchema(isOpen = false)
	interface CurrentPlayer {
		val capturedPieces: List<Int>
		val model: String
		val name: String
		val piecesInReserve: List<Int>
		val strength: String
		val timeControl: Boolean
		val useRAVE: Boolean
	}

	@DataSchema(isOpen = false)
	interface GameState {
		val bitboard: Bitboard
		val currentPlayer: CurrentPlayer
		val nextPlayer: CurrentPlayer
	}

	@DataSchema(isOpen = false)
	interface Winner {
		val loser: CurrentPlayer
		val winCondition: String
		val winner: CurrentPlayer
	}
}

In [ ]:
dataframes.map { it.head(5)  }

In [ ]:
mcts_e_vs_mcts_r

In [7]:
var concat = dataframes.concat().cast<Matrx>()

In [ ]:
concat.select {
	winner.winCondition and winner.winner.cols(0..2)
}.valueCounts()

In [ ]:
dataframes.map { it.count() }

In [ ]:
dataframes.map { it.count() }.sum()

In [8]:
val totalGames = 3000.0

In [9]:
val wins = concat.select {
	winner.winCondition and winner.winner.select { model and strength }
}.valueCounts()

In [10]:
wins.add("win_percentage") {
	(count / totalGames) * 100.0
}

winCondition,model,strength,count,win_percentage
MadeTheLastMove,MCTS,EASY,2123,70.766667
MadeTheLastMove,MINIMAX,EASY,1569,52.300000
MadeTheLastMove,MINIMAX,GREEDY,1414,47.133333
CapturedAllGIPFPieces,MCTS,EASY,567,18.900000
CapturedAllGIPFPieces,MINIMAX,EASY,194,6.466667
MadeTheLastMove,MCTS,RANDOM,66,2.200000
CapturedAllGIPFPieces,MINIMAX,GREEDY,40,1.333333
CapturedAllGIPFPieces,MCTS,RANDOM,27,0.900000

In [11]:
val winning = concat.select {
	winner.winner.select { model and strength }
}.valueCounts()

In [12]:
winning.add("win_percentage") {
	(count / totalGames) * 100.0
}

model,strength,count,win_percentage
MCTS,EASY,2690,89.666667
MINIMAX,EASY,1763,58.766667
MINIMAX,GREEDY,1454,48.466667
MCTS,RANDOM,93,3.100000

In [13]:
// 1. Isolate the winner columns (including the unique seed)
val winners = concat.select {
	seed and winner.winCondition
}.rename { colsOf<String>() }.into { "winner_${it.name}" }

// 2. Isolate and rename the current player columns
val currentPlayers = concat.select {
	seed and winner.winner.select { name and model and strength }
}.rename { colsOf<String>() }.into { "winner_${it.name}" }

// 3. Isolate and rename the next player columns
val nextPlayers = concat.select {
	seed and winner.loser.select { name and model and strength }
}.rename { colsOf<String>() }.into { "loser_${it.name}" }

// 4. Join them all together on the 'seed' column
winners
//	.join(currentPlayers, "seed")
	.join(nextPlayers, "seed")
	.remove("seed") // Optional: remove if you don't want seed included in the valueCounts
	.valueCounts()

winner_winCondition,loser_name,loser_model,loser_strength,count
MadeTheLastMove,WHITE,MCTS,RANDOM,1385
MadeTheLastMove,BLACK,MCTS,RANDOM,1370
MadeTheLastMove,WHITE,MINIMAX,GREEDY,658
MadeTheLastMove,BLACK,MINIMAX,GREEDY,531
MadeTheLastMove,WHITE,MINIMAX,EASY,529
MadeTheLastMove,BLACK,MINIMAX,EASY,408
CapturedAllGIPFPieces,BLACK,MINIMAX,GREEDY,194
MadeTheLastMove,WHITE,MCTS,EASY,180
CapturedAllGIPFPieces,WHITE,MINIMAX,EASY,171
CapturedAllGIPFPieces,WHITE,MINIMAX,GREEDY,163
CapturedAllGIPFPieces,BLACK,MINIMAX,EASY,129
MadeTheLastMove,BLACK,MCTS,EASY,111
CapturedAllGIPFPieces,BLACK,MCTS,RANDOM,83
CapturedAllGIPFPieces,WHITE,MCTS,RANDOM,69
CapturedAllGIPFPieces,BLACK,MCTS,EASY,10
CapturedAllGIPFPieces,WHITE,MCTS,EASY,9

In [15]:
// 1. Isolate the winner columns (including the unique seed)
val winners = concat.select {
	seed and winner.winner.select { name and model and strength }
}.rename { colsOf<String?>() }.into { "winner_${it.name}" }

// 3. Isolate and rename the next player columns
val nextPlayers = concat.select {
	seed and winner.loser.select { name and model and strength }
}.rename { colsOf<String?>() }.into { "loser_${it.name}" }

// 4. Join them all together on the 'seed' column
winners
//	.join(currentPlayers, "seed")
	.join(nextPlayers, "seed")
	.remove("seed") // Optional: remove if you don't want seed included in the valueCounts
	.valueCounts()

winner_name,winner_model,winner_strength,loser_name,loser_model,loser_strength,count
WHITE,MCTS,EASY,BLACK,MCTS,RANDOM,499
BLACK,MCTS,EASY,WHITE,MCTS,RANDOM,499
BLACK,MINIMAX,EASY,WHITE,MCTS,RANDOM,481
WHITE,MINIMAX,EASY,BLACK,MCTS,RANDOM,480
BLACK,MINIMAX,GREEDY,WHITE,MCTS,RANDOM,474
WHITE,MINIMAX,GREEDY,BLACK,MCTS,RANDOM,474
BLACK,MCTS,EASY,WHITE,MINIMAX,GREEDY,447
WHITE,MCTS,EASY,BLACK,MINIMAX,GREEDY,446
BLACK,MCTS,EASY,WHITE,MINIMAX,EASY,433
WHITE,MCTS,EASY,BLACK,MINIMAX,EASY,366
BLACK,MINIMAX,EASY,WHITE,MINIMAX,GREEDY,348
WHITE,MINIMAX,EASY,BLACK,MINIMAX,GREEDY,253
BLACK,MINIMAX,GREEDY,WHITE,MINIMAX,EASY,247
WHITE,MINIMAX,GREEDY,BLACK,MINIMAX,EASY,152
BLACK,MINIMAX,EASY,WHITE,MCTS,EASY,134
WHITE,MINIMAX,EASY,BLACK,MCTS,EASY,67
BLACK,MINIMAX,GREEDY,WHITE,MCTS,EASY,54
WHITE,MINIMAX,GREEDY,BLACK,MCTS,EASY,53
WHITE,MCTS,RANDOM,BLACK,MINIMAX,GREEDY,26
BLACK,MCTS,RANDOM,WHITE,MINIMAX,GREEDY,26

In [16]:
// 1. Isolate the winner columns (including the unique seed)
val winners = concat.select {
	seed and winner.winner.cols(1..2)
}.rename { colsOf<String?>() }.into { "winner_${it.name}" }

// 3. Isolate and rename the next player columns
val nextPlayers = concat.select {
	seed and winner.loser.select { model and strength }
}.rename { colsOf<String>() }.into { "loser_${it.name}" }

// 4. Join them all together on the 'seed' column
winners
//	.join(currentPlayers, "seed")
	.join(nextPlayers, "seed")
	.remove("seed") // Optional: remove if you don't want seed included in the valueCounts
	.valueCounts()

winner_model,winner_strength,loser_model,loser_strength,count
MCTS,EASY,MCTS,RANDOM,998
MINIMAX,EASY,MCTS,RANDOM,961
MINIMAX,GREEDY,MCTS,RANDOM,948
MCTS,EASY,MINIMAX,GREEDY,893
MCTS,EASY,MINIMAX,EASY,799
MINIMAX,EASY,MINIMAX,GREEDY,601
MINIMAX,GREEDY,MINIMAX,EASY,399
MINIMAX,EASY,MCTS,EASY,201
MINIMAX,GREEDY,MCTS,EASY,107
MCTS,RANDOM,MINIMAX,GREEDY,52
MCTS,RANDOM,MINIMAX,EASY,39
MCTS,RANDOM,MCTS,EASY,2

In [17]:
// 1. Isolate the winner columns (including the unique seed)
val winners = concat.select {
	seed and turn and winner.winCondition and winner.winner.select { model and strength }
}.rename { colsOf<String?>() }.into { "winner_${it.name}" }

// 3. Isolate and rename the next player columns
val nextPlayers = concat.select {
	seed and winner.loser.select { model and strength }
}.rename { colsOf<String?>() }.into { "loser_${it.name}" }

// 4. Join them all together on the 'seed' column
winners
//	.join(currentPlayers, "seed")
	.join(nextPlayers, "seed")
	.remove("seed") // Optional: remove if you don't want seed included in the valueCounts
	.valueCounts()

winner_winCondition,winner_model,winner_strength,loser_model,loser_strength,count
MadeTheLastMove,MINIMAX,GREEDY,MCTS,RANDOM,939
MadeTheLastMove,MCTS,EASY,MCTS,RANDOM,924
MadeTheLastMove,MINIMAX,EASY,MCTS,RANDOM,892
MadeTheLastMove,MCTS,EASY,MINIMAX,GREEDY,660
MadeTheLastMove,MCTS,EASY,MINIMAX,EASY,539
MadeTheLastMove,MINIMAX,EASY,MINIMAX,GREEDY,495
MadeTheLastMove,MINIMAX,GREEDY,MINIMAX,EASY,368
CapturedAllGIPFPieces,MCTS,EASY,MINIMAX,EASY,260
CapturedAllGIPFPieces,MCTS,EASY,MINIMAX,GREEDY,233
MadeTheLastMove,MINIMAX,EASY,MCTS,EASY,182
MadeTheLastMove,MINIMAX,GREEDY,MCTS,EASY,107
CapturedAllGIPFPieces,MINIMAX,EASY,MINIMAX,GREEDY,106
CapturedAllGIPFPieces,MCTS,EASY,MCTS,RANDOM,74
CapturedAllGIPFPieces,MINIMAX,EASY,MCTS,RANDOM,69
MadeTheLastMove,MCTS,RANDOM,MINIMAX,GREEDY,34
CapturedAllGIPFPieces,MINIMAX,GREEDY,MINIMAX,EASY,31
MadeTheLastMove,MCTS,RANDOM,MINIMAX,EASY,30
CapturedAllGIPFPieces,MINIMAX,EASY,MCTS,EASY,19
CapturedAllGIPFPieces,MCTS,RANDOM,MINIMAX,GREEDY,18
CapturedAllGIPFPieces,MCTS,RANDOM,MINIMAX,EASY,9

In [ ]:
mm_e_vs_mcts_e.turn.values().plus(mcts_e_vs_mm_e.turn.values()).average()
mm_e_vs_mcts_e.turn.values().plus(mcts_e_vs_mm_e.turn.values()).max()

In [ ]:
mm_e_vs_mcts_e.turn.values().plus(mcts_e_vs_mm_e.turn.values()).max()

In [18]:
concat.turn.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,p25,median,p75,max
turn,Int,6000,138,0,55,158,68.961667,19.957962,20,55.000000,66.000000,80.000000,240

In [23]:
concat.turn.mean() + 1.96 * concat.turn.std().div(sqrt(6000.0))

69.46667278456603

In [42]:
// 1. Isolate the winner columns (including the unique seed)
val winners = concat.select {
	seed and turn and winner.winner.select { model and strength }
}.rename { colsOf<String?>() }.into { "winner_${it.name}" }

// 3. Isolate and rename the next player columns
val nextPlayers = concat.select {
	seed and winner.loser.select { model and strength }
}.rename { colsOf<String?>() }.into { "loser_${it.name}" }

// 4. Join them all together on the 'seed' column
winners
//	.join(currentPlayers, "seed")
	.join(nextPlayers, "seed")
	.remove("seed") // Optional: remove if you don't want seed included in the valueCounts
	.groupBy { "winner_model" and "winner_strength" and "loser_model" and "loser_strength" }.mean()

winner_model,winner_strength,loser_model,loser_strength,turn
MCTS,EASY,MCTS,RANDOM,55.397796
MCTS,RANDOM,MCTS,EASY,47.500000
MINIMAX,EASY,MCTS,EASY,79.507463
MCTS,EASY,MINIMAX,EASY,79.117647
MCTS,EASY,MINIMAX,GREEDY,72.640538
MINIMAX,GREEDY,MCTS,EASY,75.719626
MINIMAX,EASY,MCTS,RANDOM,67.431842
MCTS,RANDOM,MINIMAX,EASY,83.256410
MCTS,RANDOM,MINIMAX,GREEDY,78.538462
MINIMAX,GREEDY,MCTS,RANDOM,69.638186
MINIMAX,GREEDY,MINIMAX,EASY,69.348371
MINIMAX,EASY,MINIMAX,GREEDY,67.224626

In [6]:
// Assuming `gamesDf` is your DataFrame<SearchInfo>
val turnDurationsLong = raveMCTS
	.select {
		seed and gameId and
				gameState.turnDuration
	}
	// Step 1: Unpack the nested gameState.turnDuration object
	.flatten()

turnDurationsLong

org.jetbrains.kotlinx.jupyter.exceptions.ReplCompilerException: at Cell In[6], line 4, column 3: Unresolved reference: seed
at Cell In[6], line 4, column 12: Unresolved reference: gameId
at Cell In[6], line 5, column 5: Unresolved reference: gameState

In [16]:
// 1. Isolate the winner columns (including the unique seed)
val winners = raveMCTS.select {
	seed and winner.winner.select { model and iterations and useRAVE }
}.rename { colsOf<String?>() }.into { "winner_${it.name}" }

// 3. Isolate and rename the next player columns
val nextPlayers = raveMCTS.select {
	seed and winner.loser.select { model and iterations and useRAVE }
}.rename { colsOf<String>() }.into { "loser_${it.name}" }

// 4. Join them all together on the 'seed' column
winners
//	.join(currentPlayers, "seed")
	.join(nextPlayers, "seed")
	.remove("seed") // Optional: remove if you don't want seed included in the valueCounts
	.valueCounts()

winner_model,iterations,useRAVE,loser_model,iterations1,useRAVE1,count
MCTS,1000,false,MCTS,100,true,192
MCTS,1000,false,MCTS,100,false,186
MCTS,1000,false,MCTS,250,false,182
MCTS,1000,false,MCTS,1000,true,177
MCTS,250,false,MCTS,100,true,150
MCTS,100,false,MCTS,100,true,138
MCTS,250,false,MCTS,250,true,133
MCTS,1000,true,MCTS,100,true,128
MCTS,250,true,MCTS,100,true,127
MCTS,250,false,MCTS,100,false,126
MCTS,250,true,MCTS,100,false,109
MCTS,1000,true,MCTS,100,false,106
MCTS,100,false,MCTS,100,false,100
MCTS,100,true,MCTS,100,true,100
MCTS,250,false,MCTS,250,false,100
MCTS,250,true,MCTS,250,true,100
MCTS,1000,false,MCTS,1000,false,100
MCTS,1000,true,MCTS,1000,true,100
MCTS,500,false,MCTS,100,true,97
MCTS,1000,false,MCTS,250,true,96